### ISSUE TITLE
Data as Placeholder

### ISSUE THREAD

**Issue by fujiisoup** [GPflow/GPflow#105]
I would like to reuse a same model for (a lot of) different data sets, but I believe in the current implementation GPflow needs compilation every time the data has changed. 
( is it correct?)

I think TensorFlow itself has a framework to prevent such an unnecessary compilation,  placeholder.
Do you guys have a plan to update GPflow to handle data as placeholder?

**Comment by alexisboukouvalas** [comment]
This is directly related to #80 where I have described one idea how to include tensorflow placeholders.
This should help reduce the number of recompilations. 

@fujiisoup thank you for the feedback. Could you describe some scenarios, ideally via short examples, that you believe would benefit from such an improvement?

**Comment by vals** [comment]
A scenario I could think of would be to define some regression model over a gene expression time course, and change the Y-data to be different genes :)

**Comment by fujiisoup** [comment]
Thank you for your replies. 

In my study field (nuclear fusion experiment), a bunch of multi channel data (typically 100 points per 1 data set and 100,000 data sets per day) are being generated and we need to estimate their latent functions and derivatives. 
The recompilation time will be significant.

I will try to contribute (though I'm not very familiar with TensorFlow), if there are no known concern about using the placeholders.

**Comment by alexggmatthews** [comment]
@jameshensman I think @vals and @fujiisoup make a compelling case from the applications end. What do you think?

**Comment by fujiisoup** [comment]
Thanks all.

I implemented this and [#80](https://github.com/GPflow/GPflow/issues/80) features into GPflow.
see [notebook](https://github.com/fujiisoup/GPflow/blob/Placeholder/notebooks/regression_with_update_data.ipynb).

I tested it manually only for GPR and VGP.
Please let me how should I test the code and send pull_request.

**Comment by jameshensman** [comment]
Hi @fujiisoup 

This sounds great. Let's have a discussion about getting this into GPflow. To start, I have
 - merged your changes into GPflow/Placeholder,
 - Created a pull request #108 , so that we can get this into the master branch,
 - invited you to become a GPflow contributor.

Looking at the PR, the tests seem to be failing at the moment. If you accept our invitation to contribute, you'll be able to push code to GPflow/Placeholder, and tests/coverage will automatically run over at #108. Let's continue this discussion over there. 

Thanks for your efforts so far!

James.

**Comment by alexggmatthews** [comment]
@fujiisoup @jameshensman are you happy to close this issue now?
