### ISSUE TITLE
Consistency of optimizers

### ISSUE THREAD

**Issue by frgsimpson** [GPflow/GPflow#1095]
There seem to be some differences in the behaviour of the scipy optimizer in GPflow 1 vs GPflow 2.
This might be due to the different treatment of positive parameters (the positive transform sets a lower bound of 1e-6 in Gpflow 1, while in GPflow 2 it uses tfp.bijectors.Softplus without this bound).

**Comment by st--** [comment]
GPflow1 also explicitly specifies `method='L-BFGS-B'` as the default, whereas gpflow2 just lets scipy.minimize pick its default, which in our use-case turns out to be `BFGS` (which is a full-Hessian optimizer, therefore may be more aggressive and struggle with the optimisation surface, and might also be slower for large models).

**Comment by st--** [comment]
Related PRs: #1110, #1112

**Comment by st--** [comment]
@frgsimpson did you have a MWE that showcases the difference in behaviour? have the recent changes removed the difference ?

**Comment by frgsimpson** [comment]
This issue related to the lack of a default lower bound on the likelihood variance in gpflow 2, which has now been re-introduced.
