### ISSUE TITLE
gpflow installer tries to install tensorflow 1.14 despite tensorflow 1.6 being already installed

### ISSUE THREAD

**Issue by aripakman** [GPflow/GPflow#1101]
### Please fill out the template below.
___

System information:

* Python version: 3.5.2
* TensorFlow installed from (source or binary): pip3 install
* TensorFlow version (use command below): 1.6.0
* GPflow installed from (source or binary): source
* GPflow version: cloned from gihub repository on 10/16/2019 

> You can collect some of this information using our environment capture script You can also obtain the TensorFlow version with python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

... _Describe the current behavior_
when running pip3 install . on the gpflow downloaded directory, pip3 starts to download tensorflow-1.14.0, despite that the fact that tensorflow 1.6.0 is installed

... _Describe the expected behavior_

... _Code to reproduce the issue Provide a reproducible test case that is the bare minimum necessary to generate the problem._
sudo pip3 install . 

.. _Other info / logs, include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached._

**Comment by st--** [comment]
Hi @aripakman, GPflow-develop does not support older versions of tensorflow. You need at least tensorflow *1.12* to run GPflow-develop (i.e. cloned from the github repository as you did). I would strongly recommend upgrading tensorflow, but if you must use tensorflow 1.6, you will have to use an older version of GPflow. You can try v1.3.0 (`git checkout v1.3.0` if you want to keep using the git clone, or `pip install gpflow==1.3.0` if you want to get the pip package).

NB: if you want to use a package from a git repository from source, and you want to keep up with changes, you should do `pip install -e .` instead of `pip install .`. Without the `-e` ("editable") flag, pip copies the current state of the package directory to somewhere else, which means changes to the git checkout won't affect the package that you get from `import gpflow`.
