### ISSUE TITLE
Finish tips&tricks notebook for gpflow 2

### ISSUE THREAD

**Issue by awav** [GPflow/GPflow#1113]
We need something similar to tips & tricks notebook for GPflow 2.0 like we had in GPflow 1.0. Here are topics (things) which we should cover in the notebook:

- [ ] Add tips & tricks notebook
  - [ ] Explain how to share tf.Module objects between models (https://github.com/GPflow/GPflow/pull/1078)
  - [x] Model training, batching, gradient tapes
  - [x] How to copy parameters of a model to another one?
- [x] add a link to the intro_to_gpflow2.ipynb from intro.ipynb

**Comment by st--** [comment]
We also need to
- [ ] add a link to the intro_to_gpflow2.ipynb from intro.ipynb

**Comment by st--** [comment]
This isn't done yet, there are no open PRs for it either?

**Comment by awav** [comment]
We ported all notebooks, and tracking other things is better here: https://github.com/GPflow/GPflow/projects/3. Could you close the issue, if you agree?

**Comment by st--** [comment]
I'm happy to use the tracking board to track things. I just think it's useful leaving a clarifying comment when you close an issue (e.g. - issue only relates to no-longer-supported version, fixed in this or that pr, information in this issue moved to that other point), and to make sure we don't loose the information.

It might be useful to actually keep some issues (and simply link them to the notes in the project board) as space there is kinda limited, and it doesn't allow for any conversation... i.e., having the project board doesn't necessarily imply that it's not useful to have an issue that is redundant with a note.

**Comment by st--** [comment]
Actually, I think the project boards work better when you're actually using issues instead of "just" notes.

**Comment by awav** [comment]
@st--, of course, it is good to have an issue number with specifics and details attached to the task on the board. But, I don't think it is good to have an issue for the **whole board**.

**Comment by st--** [comment]
Turned the one missing item into its own issue #1287
