### ISSUE TITLE
Autoflow for kernels

### ISSUE THREAD

**Issue by markvdw** [GPflow/GPflow#12]
Should the kernel evaluation functions also be decorated with Autoflow? It would allow for easy evaluation of kernels, which is great for illustration and debugging.

**Comment by jameshensman** [comment]
hi Mark, 

Yeah, we could do with something like that to make diagnostics easier, sounds like a good plan.  

We do need the tf representation of the kernels during model construction, so we'd need to modify the code to switch off the AutoFlow during tf_mode. This might get complicated because of course the decorator _uses_ tf mode internally...

Another though is that we might want a slightly different mechanism for the kernels because of the inheritance structure: you don;t want to add a decorator line to every single kernel implementation, but just have something in the super class. 

Perhaps the way to do it is to add a eval_K function to the base class which is decorated, ad will work for all inheriting classes.

**Comment by markvdw** [comment]
Ok, this has been a while, but I added a simple `evalK` function. Can be found here: https://github.com/GPflow/GPflow/pull/63

**Comment by alexggmatthews** [comment]
Fixed in #97
