### ISSUE TITLE
Question about RobustMax

### ISSUE THREAD

**Issue by anh-tong** [GPflow/GPflow#1202]
Hi, 

Can you explain the intuition of making epsilon to be `Parameter`. This quantity is not trainable. Why don't we make it a constant tensor?

https://github.com/GPflow/GPflow/blob/b17df8b62ccf00713622464f5b2b28f9ba326740/gpflow/likelihoods/robustmax.py#L27

Thanks!

**Comment by jameshensman** [comment]
Hi @anh-tong , 

There's no reason why epsilon shouldn't be a trainable parameter. It represents the fraction of 'errors' in the labels of the dataset. I think it would be a *hard* parameter to optimize, and for that reason I think most people simply set it to a small value. 

The Robustmax likelihood is attractive because it has an analytic form for `variational_expectations`, which means no mean for Monte Carlo and so no (additional) variance in the elbo. But for most problems, I'd actually recommend the softmax form: this doesn't have tractable `variational_expectations`, so we have to use Monte Carlo, which introduces variance into the elbo, but empirically I've found the resulting elbo to be much more straightforward to optimize, and the variance is small compared to that introduced by minibatching (if you're using SVGP). 

Hope that helps.

**Comment by st--** [comment]
@anh-tong if you want to re-state your question on [stackoverflow.com with the gpflow tag](stackoverflow.com/tags/gpflow) we could cross-post the answer there which will make it much more helpful and accessible to other users in the future.

**Comment by anh-tong** [comment]
Thanks for your detailed answer.
