### ISSUE TITLE
Add shape asserts across code base

### ISSUE THREAD

**Issue by st--** [GPflow/GPflow#1241]
We have now built `gpflow.experimental.check_shapes`. It should be applied consistently to our code:

* it helps in uncovering bugs in our code and gives us more confidence our code is behaving as intended,
* it makes clear _in code_ what shapes our code expects / returns (without relying on shape comments that may easily get out of date with the code itself),
* it gives more helpful error messages to users who supply wrongly-shaped tensors as inputs.

The following modules have relevant tensorflow code that would probably benefit from a bunch of shape assertions:

- [x] gpflow.conditionals + tests.gpflow.conditionals
- [x] gpflow.config + tests.gpflow.config
- [x] gpflow.covariances + tests.gpflow.covariances
- [x] gpflow.expectations + tests.gpflow.expectations
- [x] gpflow.experimental + tests.gpflow.experimental
- [x] gpflow.inducing_variables
- [x] gpflow.kernels + tests.gpflow.kernels
- [x] gpflow.likelihoods + tests.gpflow.likelihoods
- [x] gpflow.models + tests.gpflow.models
- [x] gpflow.monitor
- [x] gpflow.optimizers + tests.gpflow.optimizers
- [x] gpflow.quadrature + tests.gpflow.quadrature
- [x] gpflow.utilities + tests.gpflow.utilities
- [x] gpflow.* + tests.gpflow.posteriors
- [x] tests.integration

If you would be willing to help with some of these, please go ahead and open PRs! :)

**Comment by awav** [comment]
Good first issue? ;)

**Comment by st--** [comment]
Well, I'm assuming people using GPflow and interested in contributing may have some familiarity with arrays and shapes - the shape _comments_ tend to be there already, and there's plenty of examples of how to do it in #1219, so it's just extrapolation from there...

**Comment by joelberkeley** [comment]
i don't think we should be including asserts on return values. that kind of thing should be checked with tests not runtime asserts. I'm also dubious about expecting users to ever have to look at the code to find out what a function does

**Comment by joelberkeley-pio** [comment]
should we be including asserts on return values? I'd have thought that kind of thing should be checked with tests not runtime asserts.

I'm also wary of expecting users to ever have to look at a function's body to find out what it does or requires. For example, I would expect the docs to include the type signature and docstring, but not the source code, and I would expect that to be sufficient to know how to use functionality

**Comment by st--** [comment]
It'd of course be good to have a bunch of tests as well, but I don't think tests and shape asserts are mutually exclusive - it's hard to have full coverage by tests (though of course we should strive for that), and shape asserts are simply an additional set of checks. Yes, we should include shapes in the docstrings as well, but they don't always reflect the code (I've fixed some in #1219), and having shape asserts in code will make it easier to spot when there are any discrepancies.

**Comment by awav** [comment]
Agree with @joelberkeley, "debugging" asserts meaningful for inputs. When one function calls another, this is awkward to have double asserts on the same value. Debugging asserts are sort of filtering preconditioners, they set what input tensors you can pass. Whereas asserts in a body are runtime checks that a function works as expected - that is actually the purpose of tests.

**Comment by joelberkeley-pio** [comment]
until I'm added as contributor, here's a note saying: add shape checks for GPR. In particular,

> Could you make an issue for GPflow and emphasize that verification should be performed on early stages?

see https://stackoverflow.com/q/60061818/5986907 for more info

**Comment by joelberkeley-pio** [comment]
here's an (SO answer)[https://stackoverflow.com/a/1957656/5986907] on this topic. They explain how checking paramters should be done with standard exceptions e.g. `tf.debugging.assert_shape` (which looks to me like a misnomer cos a) it doesn't throw `AssertionError` and b) I can't see how you can turn it off). Checking the shape of a return value, if we want to do that, should be done with an assert.

**Comment by bodin-e** [comment]
> here's an [SO answer](https://stackoverflow.com/a/1957656/5986907) on this topic. They explain how checking function args should be done with standard exceptions e.g. `tf.debugging.assert_shape` (which looks to me like a misnomer cos a) it doesn't throw `AssertionError` and b) I can't see how you can turn it off for non-debug builds). Checking the shape of a return value, if we want to do that, should be done with an assert.

I agree with the SO answer. With that phrasing, a further distinction could be made between exceptions and errors, where exceptions indicate a problem that a caller (user) might want to catch (and deal with) while an error indicate a problem that should not be caught (and execution be stopped). With that said, I'm not sure I fully follow your argument.  

The way TensorFlow 'assertions' work is that they return errors (generally ValueError) if an 'assertion' can be proven to be violated statically (during graph build time alt. eager mode runtime). If not, a returned assertion op can be added to the graph to be executed at runtime.  

Coming back to assert_shapes specifically, it can very suitably be used as a check of the validity of a collection of arguments passed as function parameters. The check itself, as it acts on meta data of 'Tensor' objects not the elements themselves, is except for in the most extreme cases _very_ cheap to run. If not used within the absolute 'inner loop' causing a very large number of calls, I wouldn't worry too much about redundant checks. As a high-level check of public interfaces, such as user instantiation of models and relatively high-abstraction level functionality like conditionals, I see no problem using it to help the user understand violations of those interfaces (i.e. incorrect usage which is not to be recovered from) as well as, where it makes sense, to clarify the code and (self) document it (such as in some cases checking outputs). When the check of incorrect state or behaviour has virtually no influence on runtime performance I'd say there is not much reason to think of non-debug and debug builds :-)

**Comment by joelberkeley-pio** [comment]
Hi bodin-e,

Calling it a misnomer was mostly to highlight that `assert_shapes` shouldn't be used in the same places one would use `assert`.

As a check for function args, agreed, it's good. In other places, I agree it provides nice (relatively) dynamic documentation, but there are a few significant concerns I have:

- If `assert_shapes` is used to check code consistency, then
  - users can't differentiate between a `ValueError` that can be caught (e.g. if args were incorrect), and one that shouldn't (e.g. because there's a mistake in the GPflow code). As I understand, one should never catch an `AssertionError`.
  - I can see it becoming a temptation to leave out tests in favour of waiting for users to inform us of errors via bug reports.

**Comment by bodin-e** [comment]
> Hi bodin-e,
> 
> Calling it a misnomer was mostly to highlight that `assert_shapes` shouldn't be used in the same places one would use `assert`.
> 
> As a check for function args, agreed, it's good. In other places, I agree it provides nice (relatively) dynamic documentation, but there are a few significant concerns I have. If `assert_shapes` is used to check code consistency, then
> 
> * users can't differentiate between a `ValueError` that can be caught (e.g. if args were incorrect), and one that shouldn't (e.g. because there's a mistake in the GPflow code). As I understand, one should never catch an `AssertionError`.
> * I can see it becoming a temptation to leave out tests in favour of waiting for users to inform us of errors via bug reports.
> 
> Given the first point, I don't think they should be used to check code consistency

I see. I don't agree that errors due to passing incorrect tensors to a function is to be caught by the caller (as in the meaning of catching an exception in runtime), but rather should lead to a crash (as early as possible and ideally clearly showing what is wrong) - but we might be using the word 'caught' differently here. 

I do take your point that in the (highly hypothetical obviously ;-)) scenario a bug is introduced in the gpflow code, then causing non-fixable errors by the user (without gpflow source code modification), that is a problem. On the other hand, if the gpflow code bug (causing the shape error) is there - is it better it causes such an error, rather than give the user incorrect output (which might not even be discovered) or alternatively a more mystical error somewhere else further down the line? 

With that said, the gpflow bug could be incorrect specification of the shape expectation (an incorrect assert_shapes shape statement) - this I agree is important to be cautious of. Unit tests are of course important to have, regardless of using assert_shapes or not. A good thing is that incorrect assert_shapes statements are very likely to fail unit tests of virtually any functionality leading to calls of such incorrect assert_shapes statements.

**Comment by yiwei-prowler** [comment]
I would think about it like this:

1. I would change my mindset and treat assertions both for inputs and outputs as "executable documentation". I usually "Go to declarations" from Pycharm to look at the source code to understand how to use the code. Assertions there, together with comments help me understand the code. This also require us to write assertions with a documentation mindset -- they should make sense to the user. For example, instead of assert_shape(result, [B, T]), we should write assert_shape(result, [batch_size, time_size]).

2. The fact that in Tensorflow, shape assertions are defined in the debugging module is wrong. Shape assertions can be use for debugging, but that should not be their only purpose. They can be powerful documentation tool at the same time.

3. Shape assertions fail loudly, unlike text comments that go out of date silently.

4. We should not require a user to read the tests to understand what's the shape of the output.

4.  Writing shape assertions for both input and outputs forces you (the author of the code) to think about correctness more. This process itself helps you deliver better code. Think this way: a test case checks if the code is correct for ONLY THE TEST INPUTS. Shape assertions check if the code is correct for ANY input.

5. Shape assertions for both inputs and outputs already helped us detect many bugs, which are not covered by any tests -- in fact, it is not easy to come up with manual tests to test all those shape situations. With assertions in place, you don't need to write any manual tests anymore, just pump in random inputs, and  if the code runs, then you are ok, otherwise, the shape assertion tells you where went wrong.
