### ISSUE TITLE
Readthedocs is still serving stale versions (e.g. "stable")

### ISSUE THREAD

**Issue by st--** [GPflow/GPflow#1297]
These are still indexed by Google, so simply searching for the docs leads people to out-of-date docs that are broken - not a good image for us! Especially as the current docs are actually working so much better...

**Comment by FabricioArendTorres** [comment]
In general I think the documentation is _very_ confusing. Isn't there some way you could include the actual version the doc is for, instead of the master/develop thing. In addition there are quite a few dead docs that are still referenced.

I feel as if I get a different version of the docs each time

**Comment by joelberkeley-pio** [comment]
this may help with this ticket https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-canonical_url

**Comment by st--** [comment]
@FabricioArendTorres please check it now that I've updated the versions, if you find any further issues with the docs please open an issue again!

This has now been resolved by [the CircleCI run in the master branch of the docs repo](https://github.com/GPflow/docs/blob/master/.circleci/config.yml) calling a [shell script](https://github.com/GPflow/docs/blob/master/tag-stable.sh) that tags the master branch at that commit with the format readthedocs expects for building its "stable" documentation.

This would also allow us to enable old versions of the docs!
