### ISSUE TITLE
tf2.2-rc1 gast requirement

### ISSUE THREAD

**Issue by marcoadurno** [GPflow/GPflow#1348]
Hi,

gpflow 2.0.0-rc1 has gast requirement 0.2.2.

TensorFlow has gast requirement 0.3.3 from 2.2-rc1, which is incompatible with gpflow requirement.

Best Regards,

Marco

**Comment by st--** [comment]
TensorFlow has some issues with installing the right version of gast - we previously had gast unpinned, but that led to failures (on the CI if I recall correctly) due to pip simply installing gast 0.3.3, which is incompatible with tensorflow 2.0 and 2.1... Do you have any ideas how to make GPflow work with both TensorFlow 2.0/1 and 2.2(rc1)?
