### ISSUE TITLE
Decomposing Uncertainty with GPflow

### ISSUE THREAD

**Issue by TimHahn1981** [GPflow/GPflow#1367]
# discussion
Hi,
is there any way to get aleatoric and epistemic uncertainty in GPflow (i.e. seperate stds)?
Best,
Tim

**Comment by st--** [comment]
Hi @TimHahn1981, thanks for your interest in GPflow! I am not quite sure what kind of answer you are expecting - you can certainly build GP models with a heteroskedastic likelihood, e.g. see the [varying noise notebook](https://gpflow.readthedocs.io/en/develop/notebooks/advanced/varying_noise.html) in the GPflow documentation. Are you looking for a model in which you model the variance with another GP, e.g. a chained GP (Saul et al, http://proceedings.mlr.press/v51/saul16.html)? The GPflow multioutput framework ([tech report](https://arxiv.org/abs/2003.01115), [example notebook](https://gpflow.readthedocs.io/en/develop/notebooks/advanced/multioutput.html)) makes this easy - though you'll still have to implement a custom likelihood. If that is what you want, it may be more helpful if you ask a question on stackoverflow.com (tagged [gpflow](http://stackoverflow.com/questions/tagged/gpflow)), so that other users can also benefit from the answer.

**Comment by st--** [comment]
Hi @TimHahn1981, without a response from you there isn't anything we can do for you, so I'm closing this issue for now. You are very welcome to re-open it with your response!

**Comment by st--** [comment]
(Note- we're in the process of adding heteroskedastic likelihoods to GPflow, see #1455)

**Comment by st--** [comment]
And we're discussing the design in the #likelihood-design channel on the gpflow.slack.com chat (invite link in GPflow's README.md)
