### ISSUE TITLE
ScipyOptimizer minimize only works for kernels with 1D or 2D input dimension

### ISSUE THREAD

**Issue by enwq** [GPflow/GPflow#1483]
When I tried to define an RBF kernel with input dimension of 3 and minimize the parameters by gpflow.train.ScipyOptimizer().minimize(), the lengthscales were still the default values and were not minimized. I'm using gpflow 1.1.

**Comment by vdutor** [comment]
Hi @enwq, 
Thanks for you bug report. Unfortunately, we stopped support for GPflow < 2.0.0 and TensorFlow < 2.0. Would it be possible for you to update your failing code to the latest version of GPflow (2.0.4) and see if your bug is still present? If this is the case, feel free to reopen this issue and post a minimal failing example that allows us to replicate your bug.
Many thanks, Vincent.
