### ISSUE TITLE
Why I already have tensorflow-gpu 2.2.0 it still search for tensorflow 2.2.0

### ISSUE THREAD

**Issue by lk1983823** [GPflow/GPflow#1509]
I have built a conda environment and have tensorflow-gpu 2.2.0 installed. However, when I use the command pip install gplow, it still "Collecting tensorflow>=2.1.0 Downloading tensorflow-2.2.0-cp37-cp37m-manylinux2010_x86_64.whl (516.2 MB)". After that I have two tensorflow versions in my environment. One is tensorflow 2.2.0, the other is tensorflow-gpu 2.2.0. 
  I wonder use my gpu edition tensorflow to support gpflow. How can I do it? Thanks!
My python edition is 3.7.6.

**Comment by awav** [comment]
Since TF2.0 `tensorflow` pip package has binaries for CPU and GPU. You don't need to install `tensorflow-gpu`, and it is a separate package. GPflow requires only `tensorflow`.

https://www.tensorflow.org/install/pip#3.-install-the-tensorflow-pip-package

**Comment by ari62** [comment]
@awav Sagemaker AMIs use tensorflow-gpu and gpflow installs : 
```
Collecting tensorflow>=2.4.0
  Using cached tensorflow-2.16.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (589.8 MB)
```
The issue with overwritting the default sagemaker's install, is sagemaker AMI's are specially made to interact with the GPU, for example they contain:
```

tensorflow-gpu @ https://framework-binaries.s3.us-west-2.amazonaws.com/tensorflow/r2.11_aws/gpu/2022-12-22-20-41/tensorflow_gpu-2.11.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
sagemaker-tensorflow @ file:///sagemaker-tensorflow-extensions
sagemaker-tensorflow-training==20.4.1
```
so it isn't clear if things will work correctly  because AWS has provided a specific tensorflow version.

Outside of sagemaker,  is tensorflow-gpu equivalent to tensorflow? Meaning pip install of one is equal to doing pip install of the other?
