### ISSUE TITLE
ARD affects regression results 

### ISSUE THREAD

**Issue by jwangjie** [GPflow/GPflow#1524]
Hi,

Say we train our GPR with input `(x1, x2)` and output `y`. I specifiy the kernel with `k = gpflow.kernels.RBF(variance=1.0, lengthscales=[1.0, 1.0])` based on [this](https://gpflow.readthedocs.io/en/master/notebooks/advanced/kernels.html#Kernels-for-higher-dimensional-input-spaces). While, if I specifiy kernel with `k = gpflow.kernels.RBF(variance=1.0, lengthscales=[1.0])` instead, i.e. `ARD=False`, I got a better regression prediction results. I was wondering can someone please give more explanation about it? What's the difference between these two choices? Many thanks.

**Comment by awav** [comment]
Hello @jwangjie. According to your description, the request fits _"How do I do ..." and other issues"_. This is the issue tracker and I would recommend you to ask your question on StackOverflow and tag it "[gpflow](https://stackoverflow.com/questions/tagged/gpflow)". Thanks!

**Comment by jwangjie** [comment]
@awav Sure, I will post my question there. Can you provide some information about the question? You guys are experts who know more about GPflow than random ones.

**Comment by markvdw** [comment]
We do monitor StackOverflow for questions with the GPflow tag. So the same people will answer the question there as here :)

While we prefer StackOverflow for questions (since it's public and easily searchable), we also have a GPflow Slack for discussions. A question like this would be appropriate there as well.
