### ISSUE TITLE
Log before sum or sum before log

### ISSUE THREAD

**Issue by shihhowie** [GPflow/GPflow#1680]
The last term in the multivariate gaussian log density
#https://github.com/GPflow/GPflow/blob/b93548d9e96ab90d0f55bf5afdcda56e699d1f7f/gpflow/logdensities.py#L101

If the determinant of the covariance matrix is the trace of the cholesky L, then shouldn't the log be taken after the reduce_sum instead of before?  We were investigating this because the negative log marginal likelihood of the GPR seemed to reach negative values after some training.

**Comment by st--** [comment]
The Gaussian density contains a factor `1/\sqrt{det(K)}` ([source](https://en.wikipedia.org/wiki/Multivariate_normal_distribution#Non-degenerate_case)), so the log of the density will contain a summand \log{1/\sqrt{det(K)}} = -\log{\sqrt{det(K)}} = -1/2 \log{det(K)}. Because K = L L^T, det(K) = det(L L^T) = det(L) det(L^T) = det(L)^2, and \log{det(K)} = 2 \log{det(L)}, and the 1/2 and 2 cancel. The determinant of a matrix is the _product_ of the eigenvalues, so the log of the determinant is the log of the product of eigenvalues or the sum of the log of eigenvalues. For a triangular matrix such as L, the eigenvalues are on the diagonal. So the code is correct as is. The marginal likelihood is strictly positive, so the log of the marginal likelihood is always well defined but can be anywhere between negative and positive infinity. Hope that helps!
