### ISSUE TITLE
Add prior regularizers to optimization based Models

### ISSUE THREAD

**Issue by jmaronas** [GPflow/GPflow#1735]
# Feature request

Add log prior to the expected log likelihood in optimization based model such as GPR (Gaussian process regression) or SVGP (Sparse variational gaussian process)

## Motivation

In the current implementation, one  can set a prior distribution over the hyperparameters of a Gpflow model, see e.g. https://gpflow.readthedocs.io/en/master/notebooks/understanding/models.html#Priors

After inspecting the source code of GPR and SVGP, I have found that the log prior is not added to the training objective. My feeling is, then, that the priors are just in GPflow for running MCMC.

Having priors as part of the objective in these models makes sense in order to regularize them. This is equivalent to performing variational inference or maximum type II log likelihood on the joint model p(Y,W|X), where W denotes the kernel parameters. Hence by linearity of expectation this amounts to adding log p(W) to the objective function (since it does not depend on the latent points f, i.e same as with MCMC).

## Proposal

Just add to the ELBO the term model.log_prior_density, which is already available in the model's attribute, see https://gpflow.readthedocs.io/en/master/gpflow/models/index.html#gpflow.models.SVGP

In the current implementation this has to be manually done by overwritting the elbo's method, since one needs to proper account for minibatch rescaling.

**Comment by st--** [comment]
The [`BayesianModel` base class](https://github.com/GPflow/GPflow/blob/develop/gpflow/models/model.py#L30) adds `log_prior_density` and `maximum_likelihood_objective` in the `_training_loss`, which is what gets called when you run `model.training_loss()` (or the return value of `model.training_loss_closure()`). Does that satisfy your use-case? If not, it'd be great to see a minimal example of what's missing where. If you think it'd be good if the documentation made this clearer, please just open a pull request to add a sentence or paragraph wherever you think it would fit best!

**Comment by jmaronas** [comment]
Mmmm I see know my problem is that rather than using the training_loss_closure, I directly call in the model's objective. For me it is clearer since it allows to understand what the specific model is pursuing (e.g VI, type II ML etc).

I have checked some tutorials and actually they use the training_loss_closure (which adds the log prior).  This is basically what I was looking for.  I will open a PR, where are the instructions for doing it for the specific case of GPFlow's doc?

**Comment by st--** [comment]
`training_loss` _is_ the model's overall objective (including log prior density), and "model's objective without log prior density" is `maximum_log_likelihood_objective` (that's why we chose a somewhat long-winded but hopefully both explicit and generic name for it). You shouldn't, in general, call `model.elbo()` for example directly. If you want to encode some constraints on what your model is, you can use e.g. `assert isinstance(model, gpflow.models.SVGP)`.

Documentation: API documentation is directly from the docstrings. Notebooks are under [`doc/source/notebooks/`](https://github.com/GPflow/GPflow/tree/develop/doc/source/notebooks).

(Note that the automatic documentation build is currently broken, see https://github.com/GPflow/GPflow/issues/1728)

**Comment by jmaronas** [comment]
okay thank you!.
