### ISSUE TITLE
Automatic AutoFlow

### ISSUE THREAD

**Issue by markvdw** [GPflow/GPflow#178]
AutoFlow is great, but currently we require two different functions to compute the result of some function that returns a tensorflow variable, and one that actually constructs the variable. Would it be possible to get AutoFlow to wrap a function that returns a tensorflow variable directly, and perform the computation if `tf_mode()` is false? In this case, don't we know that the model is *not* currently constructing the graph, and so we want to get the result of the computation?

The main issue I see here is that some functions can receive a different number of variables, or variables of a range of ranks, while AutoFlow seems to require the shapes and types beforehand. Are there any more barriers?

I think this would make testing a lot nicer. Currently I'm writing a whole bunch of tests, and I need to explicitly invoke a TensorFlow each time. It would be a lot nicer if I could just evaluate functions directly...

**Comment by jameshensman** [comment]
Hi Mark, 

> some functions can receive a different number of variables

Yeah, autoflow can't really handle optional arguments at the moment

> range of ranks

You don't have to specify the rank in autoflow:
```python
@Autoflow((tf.float64,))
def f(x):
    return x + 2
```

The pattern I've used for this is to use a build/compute pattern. So
```python
class Boop(GPflow.model.Model):
    def build_foo(self, x, bool=False):
        if bool:
            return x + 2
        else:
            return x + 4

    @Autoflow((tf.float64,))
    def compute_foo(self, x)
        return build_foo(x)

    @Autoflow((tf.float64,))
    def compute_foo_True(self, x)
        return build_foo(x, True)
```

It's not perfect, but it gets the job done. You'll find the pattern in `build_predict/predict_f/predict_y`. 

It's perhaps not as arduous as it may seem, because you can reuse the Autoflow functions across inherited classes. For example, in the Kern class we define an AutoFlow `compute_K` function, which calls the kernel function(called `K`, but perhaps would be better called `build_K`), which is then defined differently in all the inherriting classes. 

If you still have a use-case for a more complex AutoFlow, we can certianly think about it.

**Comment by markvdw** [comment]
Hmm ok. This is the solution I've gone for in the end.
