### ISSUE TITLE
Multivariate Gaussian likelihood

### ISSUE THREAD

**Issue by markvdw** [GPflow/GPflow#186]
Currently, there is only support for univariate likelihoods. I'm interested in having an observation Y that depends on D latent GPs through some emission matrix. This could be implemented as a likelihood class as well.
- Would this be something you'd want to include in GPflow?
- Do you have any ideas of how to test `variational_expectations()`? It doesn't look like the quadrature would work for multiple dimensions. Have you thought about this?

**Comment by fujiisoup** [comment]
It sounds similar to what I am preparing outside GPflow (not yet uploaded to GitHub).

I guess your likelihood is something like p(Y| A F, var) with a certain matrix A.
If your likelihood is independent (it is not my case though)
p(Y| A F, var) = \Prod_i p(yi | [A F]_i, var) 
the use of a new kernel A K A^T and with a normal Gaussian likelihood may be an option.

Otherwise (in my case), I guess `vgp`,  `svgp`, `sgpmc`  do not work because the current implementation assumes independent likelihoods.

And as far as I know, the multivariate quadrature is practically impossible calculation cost increases exponentially with dimension.
We have to rely on the stochastic integration? I am also interesting to any idea.

**Comment by markvdw** [comment]
I'm interested in this because I'm implementing a variational dynamical system. In this case, because of noise in the latent state, it's not possible to just change the kernel, and a real multivariate likelihood is needed.

Currently, my tests rely on Monte Carlo estimation of the integrals to test for correctness. The issue here is that some estimates can have quite high variance, especially when the integral is like a covariance.

My feeling is that multivariate quadrature should be feasible for low dimensions. While it may be possible to get a good MC estimator, it would require some tricks in cases where the variance is high. While I think (or expect) that an easy to implement quadrature would perform better than a naive monte carlo estimate in low dimensions. And the easy to implement, understand and verify properties are important in tests.

**Comment by fujiisoup** [comment]
I guess some large modification is also necessary for `vgp`, `svgp`, `sgpmc` for using this likelihood, 
but I am interesting in this.
