### ISSUE TITLE
Issues regarding predictions on my input training and testing data.

### ISSUE THREAD

**Issue by Pranav110500** [GPflow/GPflow#1939]
Is there any way to use a normal prediction function? I mean in GPflow as of now, I only have an idea about predict_f, predict_y but they return just the mean for my set of testing data. Is there any way to get predictions that are not mean values? You can go through my code and please let me know how my output pred_y is coming all constant, as I have no idea how to visualize it. (pred_y needs to be the same as y_train actually as I've used predict_f on x_train to get it)

[GPflowOutput.pdf](https://github.com/GPflow/GPflow/files/9108367/GPflowOutput.pdf)

**Comment by jesnie** [comment]
Gaussian processes are a probabilistic framework. We will always make predictions as a mean, and an uncertainty around that mean. Generally `predict_f` and `predict_y` are the correct methods to use.

What do you mean `pred_y` is all constant? On your plots it looks like there's a nice slope to your predictions? Can you plot `pred_y` and `train_y` in the same plot, to see how far away from your data your predictions are?

In your `.pdf` I cannot see the learned parameters in your `print_summary...`. If you think the predictions are too smooth you may have too high a noise variance or too long a lengthscale - initially you can try setting these parameters manually, instead of optimising them, and seeing whether you manually can find better values. If it turns out you've been learning bad values you can place a prior on them to bias them towards a "better" value.

**Comment by Pranav110500** [comment]
Hi Sir,
The basic doubt that I have is regarding the working of the predict_f function. I have added (X_train,Y_train) in the model, but later on (**on page 5**) the predictions of the same X_train aren't coming out to be the same as Y_train. 

This is the main issue I'm having here. By all constant I mean that technically the slope shouldnt be that way, as for the different lat,long values in the grid (similar to in X_train), the output moisture predicitons should be ranging between 44 to 60 (like Y_train), and I'd assume that on the grid it should give a rather irregular pattern rather than the constant straight slope.

**Comment by jesnie** [comment]
I cannot copy n' paste from your document, so I cannot run your code, so that makes it very hard for me to debug. Also, your document sometimes cuts stuff off from the right side.

The GPR will try to separate signal from noise. If it's predicting a value that is "too smooth" and far away from you data then it's probably because it thinks that your data is mostly noise, and has very little signal. To model a low noise you want your `GPR(..., noise_variance)` (which is the same as `model.likelihood.variance`) to be a small number, but don't set it to 0 outright - that can give numerical problems. I cannot see your current values, because they're cut off from the right side of the document.

If you believe there is no, or very little, noise in your data try setting the `noise_variance` to a small number, and don't optimize it:
```python
model = gpflow.models.gpr.GPR(data=(X_train, Y_train) kernel=soil, noise_variance=1e-5)
gpflow.set_trainable(model.likelihood.variance, False)
```

**Comment by Pranav110500** [comment]
Oh, since you're unable to go through the code in its pdf format, I'm adding the link to the colab notebook directly which you may be able to access and check out. Please do let me know if you're able to analyze it better through that and check the issue.

https://colab.research.google.com/drive/1lNJLAmfECBSJoNU9hFu-JY2vg81ejFlS?usp=sharing

**Comment by Pranav110500** [comment]
@jesnie Sir could you go through the colab file and let me know as to what can be done to help get the predictions on track? Like simply predicting for X_train isn't producing the Y_train that is part of the data, hence I'm a little confused about it. I am adding the X_train, Y_train data also here in a link, please go through it if you need it for running the code.

https://docs.google.com/spreadsheets/d/1HlsTMd0_7M7CI3VXfZYsP9wrc4Yw_T74Y3mFQXD6jEI/edit?usp=sharing

**Comment by jesnie** [comment]
Try something like this:
https://colab.research.google.com/drive/1IkZgY7q-t52WuNWOzSFCofnUjE5kvLbs?usp=sharing
By playing with the strength of the prior, or disabling training of the noise variance completely you can certainly make the model "go through" the data points, but it's hard for me to judge whether that's actually correct, given the small dataset.
