### ISSUE TITLE
Require Python 3 compatability? Switch over to Python 3? If so maintain Python 2 compatability?

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#203]
My personal take at the moment:

1) No
2) No
3) If yes to 2) then definitely yes.

I am happy to discuss though if others have differing opinions.

**Comment by alexggmatthews** [comment]
It would help if we had things like this as in #102

**Comment by markvdw** [comment]
My take would be:
1) Yes
2) If you want
3) Yes

I use Python 3 for all my Python coding at the moment, including GPflow. I'm not really clued into the advantages of Python 3, except that I've found it removes a bunch of annoying inconsistencies. Things are now by default iterators etc... While I don't break Python 2 compatibility in GPflow code, I do in my own. It's nice.

Essentially, my take is that it hasn't taken a lot of effort to support Python 3 at the moment, and it's been easy to write Python 2 compatible code. So since Python 3 is the future, and switching is going to happen eventually, why not just keep up with things now?

**Comment by jameshensman** [comment]
I also advocate for python 3. As I see it:

For python 3
- python 3 removes some quirks of python 2
- python 3 adds some nice new features

For python2:
 - lots of people have python 2 installed already (but anaconda makes python 3 installation easy)

So that's a Yes, Yes, Yes, from me. 

tensorflow supports python 3, I think we should too. I'm in the same boat as @markvdw , I have been using python 3 for ages.

**Comment by jameshensman** [comment]
It should be easy to get codeship to run the tests in both python2 and python3 if we want, using virtualenvs. Although it's going to take twice as long :(

**Comment by markvdw** [comment]
If running tests for both is a problem, I think a good compromise is to test using python2, but to develop for python3. So we won't guarantee that python3 is tested, but if someone finds a bug, we will fix it.

It's happened I think once where a bug for python3 slipped in without the tests noticing it. But I found it immediately since I use GPflow on a day-to-day basis. Running the tests locally immediately pinpointed the issue.

**Comment by alexggmatthews** [comment]
Thanks for the replies. These are all good points.

I've had people telling me Python 3 is the future for the last 5 years. As Mark says it will eventually be what everyone uses but until then supporting two languages is an extra overhead for a small team of software engineers. 

An example from @jameshensman  - Doubling our test times seems to completely out weigh any fringe benefit given that Python 2 is already a good language. If we don't test in Python 3 then we are going to have to constantly ensure compatibility by hand which will also slow us down. See for example #200 . 

I really don't think we can stop supporting Python 2 and it seems everyone on the thread agrees. It is too heavily used.

**Comment by alexisboukouvalas** [comment]
my 2 cents - I have also switched to using Pytnon 3 after I was bitten by python 2 inconsistencies (e.g. integer division).
But I agree with @alexggmatthews , most people still using python 2 so it's most critical not to break and as @markvdw has said, we will notice any python 3 breaks.

**Comment by alexggmatthews** [comment]
Thanks @alexisboukouvalas . It seems many people are using Python 3 as well.

Musing on this. It would help if we had the resources to parallelize the test server. We'd get the benefit of automatically ticking all three boxes without the developer slow down. Hmm.

**Comment by jameshensman** [comment]
"most people are using python2" <=/=> "3 of the four people on this thread are using python 3"

**Comment by alexggmatthews** [comment]
It's not just a question of using Python 2 yourself it is a question of the other libraries you want to import, particularly other academic ones.

**Comment by jameshensman** [comment]
True. Which were you thinking of in particular?

**Comment by alexggmatthews** [comment]
Off the top of my head I've been testing our code against climin in the last week . It is tested using Python 2.7

https://github.com/BRML/climin

**Comment by markvdw** [comment]
I think the case is clear that python2 should be supported, since other libraries may be python2 only.

The question I still see as open is whether python3 should *also* be supported. My take is that it really doesn't take a lot of effort to do this. It never really takes more than a line change to support both.

The un-spoken policy that I've inferred from the behaviour here seemed to be something like:
- Test against Python2
- If something breaks in Python3, we care, and we'll fix it
- We notice if something breaks in Python3, because 3 active developers use it, but it will be a bit more unstable.

Personally I'm quite happy with this arrangement. Again, I haven't noticed slowdown in developing for both, and I'm also happy to contribute python3 fixes where needed.

**Comment by alexisboukouvalas** [comment]
Regarding libraries, some indeed do not work on python 3 - recently I had a case with one computational biology package (https://github.com/epierson9/ZIFA) that required some fixing up.
My experience has been : with python 2.7 pretty much everything I install will work, with python 3 there may be issues. 

If it is relatively painless to also ensure python 3 compatibility I would support that but would prioritize python 2 compatibility.

**Comment by jameshensman** [comment]
One simple way to test both python 2 and 3 would be to have them run on different services. Travis could run python 3, for example, whilst codeship covered python 2...?

**Comment by alexggmatthews** [comment]
Seems a bit strange to use two different services but I can't think of an actual reason why it would be bad. It might be the best solution currently given all the constraints.

**Comment by alexggmatthews** [comment]
OK given that the frequency of posts has decreased I'm going to call this one in favour of James' proposal. To summarize

A) We support python 3
B) We support python 2
C) To merge code needs to meet criteria 1) and 2)
D) To stop A) B) and C) from grinding us to a halt we implement the @jameshensman  suggestion about two parallel CI providers.  I'll put this on a separate ticket. 
E)  Since both A) and B) are both true we don't "move over" to Python 3 as such.
F) We keep everything under review to make sure we've made the right decision.

If F) fails we reopen this issue. Thank you all very much for your input. That was really productive.

**Comment by lyxm** [comment]
https://github.com/GPflow/GPflow/blob/master/gpflow/core/base.py#L18
Is this violation of B?

**Comment by markvdw** [comment]
The new GPflow release supports only Python 3, see https://github.com/GPflow/GPflow/issues/516.

**Comment by zzzace2000** [comment]
I will recommend updating it in the README file that it only supports python3 now.
