### ISSUE TITLE
Numpy ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by PabloLeon** [GPflow/GPflow#22]
I get am import error when trying to import GPflow:
"ImportError: numpy.core.multiarray failed to import"
I have followed the pip installation advice (on a Ubuntu machine with Python 2.7.6) and downgraded numpy to version 1.9.3.

**Comment by alexggmatthews** [comment]
Hi Pablo,
Thanks for your interest in GPflow . 
What happens if you leave GPflow out of the loop and just try to import numpy?
Could you include the full error message please?
Thanks,
Alex

**Comment by PabloLeon** [comment]
Thanks for the quick response Alex! 
Here is the full log (after import GPflow):

RuntimeError: module compiled against API version a but this version of numpy is 9
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hernals/GPflow/GPflow/__init__.py", line 1, in <module>
    from . import likelihoods, kernels, param, model, gpmc, sgpmc, priors, gpr, svgp, vgp
  File "/home/hernals/GPflow/GPflow/likelihoods.py", line 1, in <module>
    import densities
  File "/home/hernals/GPflow/GPflow/densities.py", line 1, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 45, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: numpy.core.multiarray failed to import

the normal numpy import works fine!

**Comment by alexggmatthews** [comment]
Hmm OK this is odd I haven't seen this problem,

Do you get the same problem if you install the standard tensorflow? (This won't work with GPflow)

pip uninstall tensorflow
pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl
python
import tensorflow as tf

You will need to reinstall our version of tensorflow after doing this.

**Comment by PabloLeon** [comment]
Thanks Alex! Tensorflow doesn't have any problems, I can import it after following the steps above.

**Comment by alexggmatthews** [comment]
Hi Pablo,
I'm afraid I'm now off for the long weekend. It looks like some sort of problem with your exact packages which is going to be difficult to track down remotely. 

I'm not sure if this will help or not in the meantime but here is what I do to setup GPflow from scratch on an Amazon ECII instance. I understand you may not want to do this because you have other software using python but maybe it will help to see at least one working route. 

sudo apt-get update #Updates ubuntu
wget https://3230d63b5fc54e62148e-c95ac804525aac4b6dba79b00b39d1d3.ssl.cf1.rackcdn.com/Anaconda2-2.4.1-Linux-x86_64.sh #Gets anaconda python bundle
bash Anaconda2-2.4.1-Linux-x86_64.sh #Installs anaconda python need to follow instructions and make sure path on .bashrc
source ~/.bashrc #reloads .bashrc to add anaconda to path. Runs automatically for starting a command line session but not for an ssh session.
pip install http://mlg.eng.cam.ac.uk/matthews/GPflow/python_packages/version_0.1/linux/tensorflow-0.6.0-py2-none-any.whl #Installs our TensorFlow fork. 
sudo apt-get install git #install git
git clone https://github.com/GPflow/GPflow #clones GPflow
cd GPflow 
python setup.py develop #sets up GPflow paths etc.
cd notebooks
python simple_regression.py #Simple demo example. 

hth,
Alex

**Comment by alexggmatthews** [comment]
Sorry I will try that again (I just deleted a  post contained error).

I'm afraid I'm off for the long weekend now. It looks like some clash with your specific packages that is going to be difficult to track remotely. It might be an idea to have a look at the Travis file in the route of the source to see how we install it for test in the meantime.

**Comment by PabloLeon** [comment]
I've now build from source and get a different error:
```
import GPflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "GPflow/__init__.py", line 1, in <module>
    from . import likelihoods, kernels, param, model, gpmc, sgpmc, priors, gpr, svgp, vgp
  File "GPflow/model.py", line 3, in <module>
    from scipy.optimize import minimize, OptimizeResult
ImportError: cannot import name OptimizeResult
```

I've update to the most recent scipy version (scipy==0.17.0) and  import minimize works - it is the OptimizeResult that fails. OptimizeResults shows up on the docs for 0.17. but I cannot import it. Any ideas? Which scipy version are you running on?

**Comment by jameshensman** [comment]
Hi @PabloLeon , I'm using 

python 2.7.11 
Anaconda 2.1.0 (x86_54)
scipy 0.17
numpy 1.10.4
osx 

for what it's worth, the following works fine for me:
```python
from scipy.optimize import OptimizeResult
```

Are you using python 3, perhaps? Please list your environment, and we'll try to help.

**Comment by alexggmatthews** [comment]
Did you ever follow this up @PabloLeon ?

**Comment by PabloLeon** [comment]
Sorry wasn't around a while... I have both python2/3 on my work machine. I installed (and used) python for everything related to GPflow though (and all dependencies etc. are installed for python 2). I will have a look at it on Monday and update this.

**Comment by PabloLeon** [comment]
I needed to reset my machine and opted to go for the Anaconda setup. Everything seems to work fine now. Thanks for the help!

**Comment by alexggmatthews** [comment]
Great! Thanks for sticking at it. Alex
