### ISSUE TITLE
SVGP: Why doesn't my posterior mean go through the data?

### ISSUE THREAD

**Issue by markvdw** [GPflow/GPflow#230]
Why does the following code, produce the image below? Since I set I would expect the posterior mean to go through the appropriate value of `sm.q_mu` at the inducing point location?

```
sm = GPflow.svgp.SVGP(d.X, d.Y, GPflow.kernels.RBF(1), Z=np.array([0.0, 2.0, 7.0, 8.0])[:, None],
                      likelihood=GPflow.likelihoods.Gaussian())
sm.Z = np.array([0.0, 3.0, 7.0, 8.0])[:, None]
sm.likelihood.variance = 0.001
sm.q_mu = np.array([-1.5, 1.0, -0.5, .5])[:, None]
sm.q_sqrt = np.linalg.cholesky(np.array(
    [[0.01, 0.000, 0.0, 0.0],
     [0.000, 0.01, 0.0, 0.0],
     [0.0, 0.0, 0.01, 0.009],
     [0.0, 0.0, 0.009, 0.01]]
))[:, :, None]
pY, pYv = sm.predict_f(pX)
plt.plot(pX, pY)
pYo = pYv**0.5 * 2.0
plt.fill_between(pX.flatten(), (pY - pYo).flatten(), (pY + pYo).flatten(), linewidth=0.0, alpha=0.1)
plt.plot(sm.Z.value, sm.q_mu.value, 'ro')
```
![](http://i.imgur.com/pJwvpCn.png)

**Comment by fujiisoup** [comment]
Hi @markvdw 

It is because SVGP adopts the whitened representation by default, i.e.
the posterior mean and variance are represented as `u = L*q_mu` and `cov = L*q_sqrt * q_sqrt^T * L^T`.
(where `K = L*L^T`)

To represent the posterior directly, set `whiten` flag False,
`sm = GPflow.svgp.SVGP(d.X, d.Y, GPflow.kernels.RBF(1), Z=np.array([0.0, 2.0, 7.0, 8.0])[:, None],
                      likelihood=GPflow.likelihoods.Gaussian(),
                      whiten=False)`

**Comment by markvdw** [comment]
Damn, that comes back to haunt me too often! Thanks a lot!
