### ISSUE TITLE
overflow encountered in exp (model optimization)

### ISSUE THREAD

**Issue by BPie** [GPflow/GPflow#300]
Hi 
I've encountered a problem while optimizing a GPR model

[file](http://pastebin.com/uiAR1zpN)

and I get 
```
/home/xyz/.virtualenvs/tf_0_11/bin/python /home/xyz/workspace/studia/mgr/kod/pypilco/sandbox/regression.py
/home/xyz/.virtualenvs/tf_0_11/lib/python2.7/site-packages/GPflow-0.3.4-py2.7.egg/GPflow/transforms.py:129: RuntimeWarning: overflow encountered in exp
  return np.log(1. + np.exp(x)) + self._lower
(...)
```
PS If I have some more questions (that can be trivial for someone) I should post theme here as Issues, mail them to someone, post somewhere or It would be best not to bother you with those at all?

**Comment by markvdw** [comment]
I can't really go through the entire piece of code to find the cause. It would be more helpful to get a minimum working example.

This may be obvious, but it looks like one of the positively constrained hyperparameters becomes rather large during optimisation, causing the overflow. This is usually caused by an odd dataset or by strange optimiser dynamics.

Dataset features could be if one dimension has no variation and `ARD=True`. This causes the optimum for the appropriate lengthscale to lie at infinity. Alternatively similar things can be caused by the range of the datasets being very large. Normalising the input dimensions usually fixes this.

Sometimes aggressive optimisers like BFGS take very large steps when the estimated Hessians are ill-conditioned. Using nonlinear conjugate gradient (`method='cg'`) could fix this. To debug further, it may be good to log the intermediate states during optimisation by adding a callback function, e.g.:
```
hist = []
def logger(x):
    hist.append(x)
```
And then passing `callback=logger`.

I'm happy to answer any small queries here. You could post them in the same thread if you think they are small.

**Comment by jameshensman** [comment]
Discussion is welcome through these issues. Perhaps you could mark them as 'discussion' rather than 'bug' though.

@markvdw  @alexggmatthews , perhaps we should make this clearer on the front page?

**Comment by BPie** [comment]
I simplified the code but I get no exception there. I'll try to figure it out.

**Comment by markvdw** [comment]
@BPie, the dataset is odd for an RBF kernel, like I mentioned above. The input range is 0..40, similar for the output range. The relationship is close to linear too. This causes an RBF to require a much larger variance, in relation to the size of the dataset, causing the overflow. Fixes:
- Use a Linear + RBF kernel
- Normalise the dataset to keep the required variance in a sensible range.

Feel free to drop me an e-mail with any other issues you have.

**Comment by BPie** [comment]
@markvdw, thanks, that helped me to understand the issue.
