### ISSUE TITLE
Implementation Bayesian Dynamic GP-LVM

### ISSUE THREAD

**Issue by nknudde** [GPflow/GPflow#324]
Coming back to issue #321, I [implemented](https://github.com/nknudde/GPflow/blob/dynamic-gplvm/GPflow/dgplvm.py)  Bayesian Dynamic GP-LVM, based on the description in 
A. Damianou. (2015) 
"Deep Gaussian Processes and Variational Propagation of Uncertainty." 
PhD Thesis, The University of Sheffield. Supervised by Prof. Neil Lawrence.
I added a small illustration and a inittest. This is new code, so might still contain some bugs. 

By the way, I, @javdrher and @icouckuy have been working on some Manifold Relevance Detection/Multi-View GP-LVM code in GPflow also described in aforementioned PhD dissertation, would you be interested in integrating it?

**Comment by Bonnevie** [comment]
@markvdw has been talking about making a supporting package (called something like `GPflow_tools`) to include complementary work that falls a bit outside the general purview of the package. He might have something to add regarding the bit about integration of MRD etc.

**Comment by markvdw** [comment]
This is something I have discussed in the past with @jameshensman and @alexggmatthews. The consensus at the time was that GPflow should be kept focussed, and shouldn't start including a large "zoo" of models. The current (perhaps implicit) state of affairs is that the core GPflow package supports GP inference for various likelihoods, and the simplest form of the GPLVM. The reason we did this, was because the kernel expectations fit naturally in the kernel definitions in GPflow, and that these are a dependancy for all other interesting hierarchical GP models.

That said, it would be great if people want to contribute more complex models! One way to do this would be to have them as separate packages under the GPflow organisation, e.g. a specific GPLVM variants package. As another example, I'm working on a GPSSM package.

Having these packages under the GPflow organisation rather than in the core repo itself has the following benefits:
- People interested in GPflow can still easily find the derived models
- Core package is lean and can be maintained by a small number of people who all know the entire codebase (less risk of orphaned code if the contributor of a big model stops contributing).
- Ownership of contributed packages is clearer (easier to identify the main contributors)
- This also makes it clearer who's responsible for keeping things up-to-date :)

One requirement for having a model under the GPflow organisation would be that test coverage and code quality will be kept up to the standard of the core GP package (i.e. >95%, preferrably 99% test coverage). Naturally, the GPflow 'community' will be around to help with this.

**Comment by javdrher** [comment]
I understand the rationale to do so, and I think I would be happy to help with some packages. Personally for instance, I think I could initiate a GPflowOpt under this setting. And we still have some funky LVM models I think. Part of this is currently implemented internally and throughout the next weeks, we are deciding how we are going to organize our development and release of code (which also includes some unrelated things) in the future.

What would be further requirements for the derived packages? Can they have additional dependencies? We might for instance rely on some of our libraries. And what about licensing? can other packages within GPflow go with other licenses or should there be some level of uniformity?

**Comment by mathDR** [comment]
I, too, would like to know what thoughts people have in this arena.  @jameshensman and I have a GPclust package based on GPflow that (I think) would fit nicely in this space.

**Comment by jameshensman** [comment]
- As @markvdw said, packages under the GPflow banner should be of a standard that GPflow users expect. Documentation and testing should be of the same standard as GPflow. We won't create packages willy-nilly, there will have to be some good rationale and thought behind them. And someone will have to take responsibility for leading and maintaining the project.

 - Some potential packages might include:
    - GPflowOpt as stated.
    - GP state space models (under @markvdw)
    - Latent variable models (Dynamical GPLVM and variants, perhaps the Bayesian GPLVM should live there too)
    - An R implementation of GPflow (@nickgolding)

- I see no good reason to deviate from the Apache license, but am willing to be persuaded otherwise. 

- Extra dependencies are fine but GPflow packages should follow the same 'tidiness' principles as GPflow, keeping the package lean and maintainable. A rule of thumb might be that 'core python scientific stack' are okay dependencies: one should be cautious about depending packages that are not well maintained (e.g. releases of academic code) or outdated. 

- We won't necessarily accept all requests to have projects brought under the GPflow umbrella. It might be a good idea to have a page of links to projects using GPflow; I'm sure there are many.

@nknudde , @javdrher if we've not put you off adding projects to GPflow, I suggest you create issues proposing the projects. You should explicate the aims and objectives of the repo, what you have so far, and how the repo is going to be better than competing alternatives. I think it's important to have finite goals for the project, to prevent feature creep and maintenance fatigue. You should describe how your code will be structured. You should mention any changes that you would expect from GPflow/GPflow to be able to achieve your goals.

**Comment by alexggmatthews** [comment]
@jameshensman Given that your posts reflects our views on more than just Dynamic GP-LVMS should we maybe put it into the contributing and roadmap pages? I think other people would be interested to see this.

**Comment by jameshensman** [comment]
Agree

**Comment by javdrher** [comment]
Final question: what about publishing policies? If at some point, it would be interesting to write a software paper, would that be ok? If so I guess its natural to have appropriate acknowledgement or make it a joint publication.

**Comment by alexggmatthews** [comment]
@javdrher we aren't ignoring your last question. @jameshensman and I have been discussing and will reply soon. My apologies for the delay.
