### ISSUE TITLE
SGPR full predictive cov not positive definite

### ISSUE THREAD

**Issue by thangbui** [GPflow/GPflow#350]
I found that the full_cov option sometimes returns a non-positive definite predictive covariance matrix. Some code to replicate this issue. 

```python
import numpy as np
import numpy.random as rnd
import GPflow
from GPy.kern import RBF
import matplotlib.pyplot as plt
plt.style.use('ggplot')

np.random.seed(42)

M = 50
N = 100
eps = 1e-5
noise_var = 0.04

# generate traning data
X = np.random.rand(N, 1) * 10 - 5
k = RBF(1, variance=1.0, lengthscale=1)
K = k.K(X) + np.eye(N) * eps
f_true = np.random.multivariate_normal(np.zeros(N), K).reshape(-1,1)
Y = f_true + np.sqrt(noise_var) * np.random.randn(N, 1)

# build model
kern = GPflow.kernels.RBF(1, 1, 1)
Z = X[:M, :].copy()
model = GPflow.sgpr.SGPR(X, Y, kern, Z)
model.likelihood.variance = noise_var
model.likelihood.variance.fixed = True
model.optimize(disp=0)

# mx, Sx = model.predict_f_full_cov(X)
# print 'deteminant %.10f' % (np.linalg.det(Sx[:, :, 0]))
# print 'cholesky ', np.linalg.cholesky(Sx[:, :, 0])

Zu_opt = model.Z.value
mu_opt, Su_opt = model.predict_f_full_cov(Zu_opt)

# plt.plot(X, Y, '+k')
# plt.errorbar(Zu_opt, mu_opt, yerr=2*np.sqrt(np.diag(Su_opt[:, :, 0])), fmt='or')
# plt.show()

print 'deteminant %.10f' % (np.linalg.det(Su_opt[:, :, 0]))
print 'cholesky ', np.linalg.cholesky(Su_opt[:, :, 0])
```

**Comment by alexggmatthews** [comment]
Hi Thang,
Thanks for your interest in the software.

`print 'log deteminant ', (np.linalg.slogdet(Su_opt[:, :, 0]))`

Gives me:

(-1.0, -991.6947408210317)

Suggests that the determinant is very small and negative. I therefore suspect a numerical issue due to small condition number of the matrix. Since this is a relatively large predictive matrix evaluated at the inducing points themselves I'm not too surprised. 

We don't solve linear systems in the code without first adding a whitening parameter which is controlled from gpflowrc. To be consistent I would suggest adding the same amount of whitening. 

Does that help?

Thanks,
Alex

**Comment by thangbui** [comment]
That makes sense. Thanks, Alex!

Thang.
