### ISSUE TITLE
Stochastic Inference for Classification, Fixing Z

### ISSUE THREAD

**Issue by CSNoyes** [GPflow/GPflow#357]
What is the purpose of fixing and then unfixing "Z" in the documented classification example? If one were to implement stochastic variational optimization for the SVGP classification example, should Z remain fixed during optimization and if so why?

**Comment by Bonnevie** [comment]
It's a pretty fickle optimization problem since `Z` introduces many degrees of freedom - fixing `Z` and allowing the remaining hyperparameters to converge first gets the optimization routine into a more well-behaved part of the parameter space where the optimization routine can then be run as normal.

**Comment by CSNoyes** [comment]
Thanks, that makes a good bit of sense. Second question (and I apologize, the documentations parameters are difficult to map to the referenced papers), when using one of the tensorflow optimization methods (e.g. ADAM), in the documentation maxiters is set to np.inf. Is there a reason that this is the case in that example but in all others the number of iterations is a (relatively small) constant?

**Comment by jameshensman** [comment]
That sounds like an unusual choice! I guess the reason is that GPflow behaves nicely when you interrupt it (ctrl-c) so perhaps the author of that document planned on letting it run until after breakfast 😀, when he could interrupt it manually.

**Comment by alexggmatthews** [comment]
Closed due to inactivity
