### ISSUE TITLE
Assigning to subset of parameters

### ISSUE THREAD

**Issue by Bonnevie** [GPflow/GPflow#358]
Maybe I'm missing an obvious solution, but shouldn't there be a way to set a subset of the parameters? Using the parameter_dict framework seems like the obvious way to go about it, but it returns an error if the parameter_dict is not complete. 
Would it be as simple as wrapping the `Param`-level `set_parameter_dict` method in a try-catch block?

**Comment by markvdw** [comment]
You can use `d = m.get_parameter_dict()` to get a dictionary of existing parameters, do `d.update(param_subset_dict)` to set the subset, and then use `m.set_parameter_dict(d)`. I it a useful check that all parameters need to be present in `d`.

**Comment by Bonnevie** [comment]
Reasonable solution. I wanted to change the hyperparameters of multiple SGPRs with different numbers of inducing inputs, so the fact that their inducing inputs were different sizes and quantities made the fact that you couldn't get at subsets a bit messy.
Relatedly, is there a way to make a complete copy of a GP?

**Comment by markvdw** [comment]
Do you mean a copy of the object? This is a bit of a rabbit hole to do correctly, since a GP object contains references to other object. In the copied GP, do you want references to the same datasets for example? Or do you want to copy the entire dataset as well?

I usually just re-create the same GP (my model construction code is inside a function) and then set the parameters.

Alternatively, the pickling the GP is well thought through, if that helps...
