### ISSUE TITLE
Constraining and tying the length scales to have a positive semi-definite covariance

### ISSUE THREAD

**Issue by ktiwari9** [GPflow/GPflow#403]
#Is there a way to constrain the length scales or tie the length-scales together ? I have a 3-D input X and a 1-D output Y but length scales of 2 of the input dimensions must be tied together and all of the 3 lengthscales need to be constrained otherwise they explode to really high values and my covariance is no longer positive semi-definite.

Please advise.

**Comment by nknudde** [comment]
Note that in theory the covariance is always positive definite, but due to numerical problems it may not be. You could tie the lengthscales together by combining different kernels:
k1 = GPflow.ekernels.RBF(2, active_dims=[0, 1])
k2 = GPflow.ekernels.RBF(1, active_dims=[2])
k = k1 + k2

Additionaly you can restrict the values of lengthscales by using the transform parameter (k1.lengthscales.transform = GPflow.param.transforms.Logistic(lower bound, upper bound)

**Comment by st--** [comment]
Hope this is solved, but if not please re-open an issue.
