### ISSUE TITLE
feed_dict performance

### ISSUE THREAD

**Issue by 1Reinier** [GPflow/GPflow#406]
I notice that my GTX1080 rarely uses more than 30% of its GPU capacity when using GPflow.

I've had this before in TensorFlow when using `feed_dict` to supply my data, because of Python to TF copying and slow host to device transfers inherent to feeding in the data in this way (as is discussed ![here](https://github.com/tensorflow/tensorflow/issues/2919)).

Would it be an option to switch to TF queues in the future to take better advantage of compute capabilities?

**Comment by markvdw** [comment]
I've seen a similar issue with the low utilisation of the GPU. I still see a decent speed-up though.

If the speedup is really significant (i.e. you could get a factor of 3 by utilising the GPU fully), it may be worth it. Currently, since the optimisation is done outside of TensorFlow, it may require rather large changes to the code. There has been some talk in https://github.com/tensorflow/tensorflow/issues/446 on related issues.

Essentially, before working on it, I'd like to know how much the blame really is on `feed_dict`. Not all ops required (specifically the Cholesky op) are on the GPU yet, so this can also be the cause. Do you have any way of quantifying this?

**Comment by jameshensman** [comment]
This depends very much on the model. For models that are cholesky-bound, we'll see no improvement from using the gpu. In other models, I've seen cpu outperform gpu simply because tf manages to distribute the graph more effectively on the cpu. 

I'd be very happy to see a tf. Queue system ( perhaps integrated with the data holder class). If prototype code showed that a speed up was available, I'd be willing to invest some time refining an implementation. 

First step though is to have a look at the tensorflow Json-trace, which you can enable through gpflowrc. That may shed some light on why this model is slow.

**Comment by 1Reinier** [comment]
Thanks for the input. The feed_dict was just a hunch based on previous experience with CNNs, so I'll check against the json-trace it when I have time.

**Comment by st--** [comment]
Can this be closed now ?

**Comment by st--** [comment]
@1Reinier if this is still an issue with gpflow 1.x please open a new issue
