### ISSUE TITLE
Titsias evidence upper bound for SGPR

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#463]
Michalis Titsias derived an evidence upper bound for SGPR in slide 58 

http://www2.aueb.gr/users/mtitsias/papers/titsiasNipsVar14.pdf

Proved in slide 85 . Used in this recent paper by Kim and Teh:

https://arxiv.org/pdf/1706.02524.pdf

I think this would be a useful addition to GPflow and am willing to implement it with the advice of the community. @jameshensman thoughts?

**Comment by markvdw** [comment]
I've got an implementation of this. Happy to contribute.

**Comment by thangbui** [comment]
I've played with this upper bound but found that it's not as tight as the lower bound, i.e. for a decent M, the lower bound can be very good and close to the exact marginal likelihood but the upper bound is still way off the exact.

This is however potentially very useful in diagnosing how many pseudo-points are sufficient for a given dataset.

**Comment by jameshensman** [comment]
A simpler way to work out if you have enough inducing points in to compute
trace(Kff - Qff).

That's actually an upper bound on det(Kff-Qff), which is the entropy of the
conditional p(f|u). If that entropy is zero, then f is completely specified
by u and the approximation is exact.

 Perhaps we should add that as a feature also?

**Comment by alexggmatthews** [comment]
@jameshensman Could you say a bit more. Do you mean the differential entropy of the conditional p(f|u) ? Can't that be negative?

**Comment by jameshensman** [comment]
The matrix of interest is Kff-Qff. This is the variance of the conditional distribution p(f|u). The entropy of that distribution is log det Kff-Qff plus constant.  If there is no entropy in f when we know u, then u captures f perfectly, which is what we want. 

The log-trace is a simple upper Bound on the log det. The first is the log of the sum of the eigvals, the second is the sum of the log eigvals. 

Is that helpful?

The upper bound is appealing, but this trick is simpler and cheaper. This also applies in the non conjugate case, though it can't help you out with slack in the bound due to non-Gaussianity.

**Comment by alexggmatthews** [comment]
Ah OK. You've slipped in a logarithm, but what's a logarithm between friends :)

In the case where Kff = Qff we get log det 0 which equals -Inf . So the `ideal' differential entropy of p(f|u) in question is not zero it is -Inf.  

It seems though that when Kff=Qff  we get exp(Differential entropy) = 0 which corresponds up to a multiplicative constant to the det(Kff - Qff ) you started with. 

Thanks for sharing that. I'll have a think about it in a bit more detail.

**Comment by markvdw** [comment]
The upper bound relies on the similar observation that Tr(Kff - Qff) \geq eigmax(Kff - Qff). I think that the core issue to why the upper bound is so loose, is that the marginal likelihood can be vastly under-estimated with a tiny amount of entropy in the conditional p(f|u). Consider a case where N data points perfectly predict the N+1th, but there is still some extra variance introduced by the p(f|u). As this extra variance shrinks to zero, the marginal likelihood will continuously increase, right?

**Comment by alexggmatthews** [comment]
Sorry to keep going on about the -Inf thing but obviously it is relevant to the discussion at hand.

Let's modify James' original for the fact that the differential entropy of a Dirac delta is -Inf not 0.

Then part of what we are saying something like:

`The approximation has converged if \expecation_{p(f|u}[ \log p(f|u) ] = -Inf `

But this still isn't true. Take the case where an inducing input is also a data input. Then _one_ of the components of p(f|u) will be perfectly modelled but not necessarily the rest. But this still gives a differential entropy of -Inf.

**Comment by alexggmatthews** [comment]
I've corrected some typos in that - sorry.

**Comment by markvdw** [comment]
Isn't it that the implication is only `\expecation_{p(f|u}[ \log p(f|u) ] = -Inf if the approximation has converged`?

The core statement is that the approximation has converged if Kff - Qff = 0. This is implied by Tr(Kff - Qff) = 0, given the constraints on Qff. Like James said, this also implies that there is no residual uncertainty in p(f|u), and that the differential entropy is `-Inf`, since the differential entropy of a Gaussian is log det Kff-Qff (and independent of u), which is upper bounded by Tr.

However, a -Inf differential entropy does not imply that the Tr is zero, since the Tr is just an upper bound.

**Comment by markvdw** [comment]
Also, I wonder whether the differential entropy argument can be fixed by considering the differential entropy from first principles. Generally, it's constructed by an increasingly fine discretisation of a continuous distribution. The differential entropy is then the difference between the entropy of some reference (uniform) distribution and the entropy of the discretised continuous one.

In the case of an inducing variable at a data input, the infinite term can be singled out and removed by considering the distribution for offending inducing point separately. In this case, the total entropy of the discretised distribution of the offending inducing point will always be zero, while leaving the differential entropy of the rest of the inducing points unchanged. Essentially, this is just looking at the differential entropy in the subspace that does have uncertainty left in it.

If the actual entropy (not differential) of p(f|u) is zero, then I think the implication does work both ways. But, like you pointed out, this requires a bit more than just showing that the differential entropy is -inf.

**Comment by alexggmatthews** [comment]
@markvdw  says:
> The core statement is that the approximation has converged if Kff - Qff = 0. This is implied by Tr(Kff - Qff) = 0, given the constraints on Qff.

Yes that works for me. 

When Tr( Kff - Qff ) is not identically 0 as will always be the case in practice we need to think about how to interpret the units of the result. If you could fix up the differential entropy of the conditional p(f|u) we would still have the problem that the trace is a bound.

**Comment by alexggmatthews** [comment]
Thanks all for a very interesting discussion.

**Comment by alexggmatthews** [comment]
Now I think about it det(Kff - Qff) has the same problem as the one with the differential entropy right? If the covariance is degenerate the determinant will be zero even if Kff \neq Qff .

**Comment by alexggmatthews** [comment]
@markvdw gives
> Tr(Kff - Qff) \geq eigmax(Kff - Qff)

And eigmax(Kff-Qff) = 0 iff Kff = Qff
So we don't need the determinant.

**Comment by alexggmatthews** [comment]
For those following who are less familiar with this area, dividing the trace diagnostic by the noise variance relates to a very lucid discussion by Michalis Titsias on page 8:

http://www2.aueb.gr/users/mtitsias/papers/sparseGPv2.pdf

It illustrates a key caviat in the diagnostic - it measures the quality of the prior approximation at the data points but ignores the quality of the variational distribution as a model of the output data. The quality of the model is measured by other term in the objective- the DTC log marginal likelihood term. Together the two terms give a posterior approx that is good in terms of KL.

**Comment by markvdw** [comment]
There's another caveat in this diagnostic now I think about this. It only assesses the approximation quality for the current hyperparameter setting. Technically we're interested in finding the hyperparameter with the maximum marginal likelihood. Even when Kff = Qff, there may be other hyperparameter settings that are poorly approximated. This is (tangentially) illustrated in the upper bound notebook.

Even once the variational approximation has converged, there are other hyperparameter settings with upper bounds that are still loose. Technically we can only really know we've converged if the upper bound is lower than the current lower bound for all other hyperparameter settings.

**Comment by jameshensman** [comment]
Yeah, this is both a strength and a weakness of the variational approximation in and hierarchical model. 

We can only know that the bound is tight for the current hyper settings. There could always be another setting of the hyperactive where the bound is loose.

But, we hope that for many of those settings, it doesn't matter because they are irrelevant to the problem(e.g. Short length scale settings). 

The area needs a bit more study. It's tricky to optimise variational parameters alongside hypers from several angles: computationally, watching out for local minima, initialisation, natural gradients, freezing. The question of model selection is still tricky.

**Comment by thangbui** [comment]
This is slightly off topic, but I want to second James' last point by a concrete example that needs more study: Iain Murray suggested setting the initial noise to be high [see [here](https://www.cs.toronto.edu/~hinton/csc2515/notes/gp_slides_fall08.pdf)], but I found a small init noise is almost always better when using sparse approximations.

**Comment by markvdw** [comment]
#470 is ready to be merged.
