### ISSUE TITLE
jitter_level not used in GPLVM

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#467]
There is at least one place in the GPLVM code which doesn't use the` jitter_level` setting:

https://github.com/GPflow/GPflow/blob/b185159cadd147ede43762f57ca1a6ef80df7c74/GPflow/gplvm.py#L119

This can lead to Cholesky failures, particularly when working in single precision see #466 .

**Comment by alexggmatthews** [comment]
We need to go through and see if there are other examples of this.

**Comment by alexggmatthews** [comment]
@alexisboukouvalas suggests better automated test coverage on float32. I expect that would have picked this up. It would be good to do this if we can find the resources.

**Comment by alexisboukouvalas** [comment]
@alexggmatthews great catch! I fixed two such occurrences in #465 
test_gpvlm passes with float32

Other tests do not (example test_ekerns fails with type error
TypeError: Input 'y' of 'BatchMatMul' Op has type float32 that does not match type float64 of argument 'x'.)
This does suggest we need to add float32 test coverage. Perhaps a separate issue + pull request would be more appropriate rather than trying to do this in #465. Thoughts?

**Comment by markvdw** [comment]
#465 fixes this. However, the question of how to do better `float32` testing is still open.

We can close this for now?
