### ISSUE TITLE
Cholesky decomposition

### ISSUE THREAD

**Issue by NazBen** [GPflow/GPflow#503]
Hello,

I was trying to build GP models on different data samples, but sometimes, I obtained an error from the Sholesky matrix and I don't understdand the meaning. Here is a preview of the returned error :

``` 
InvalidArgumentError: Cholesky decomposition was not successful. The input might not be valid.
	 [[Node: name.build_likelihood_7/Cholesky = Cholesky[T=DT_DOUBLE, _device="/job:localhost/replica:0/task:0/cpu:0"](name.build_likelihood_7/add)]]
```

I also added an example that reproduce this kind of error:

```
import numpy as np
from scipy.stats import uniform
import gpflow
np.random.seed(0)

dim = 3
n_sample = 200
X = np.asarray([uniform(-4., 4.).rvs(n_sample)]*dim).T

test_func = lambda X: X.sum(axis=1)[:, None]
y = test_func(X)

kernel = gpflow.kernels.Matern52(dim)
m = gpflow.gpr.GPR(X, y, kern=kernel)
m.likelihood.variance = 0.
m.optimize()
m
```

It would be very helpfull if someone could enlight me.

Best regard.

**Comment by hughsalimbeni** [comment]
The error is due to setting the likelihood variance to zero (you'll get nans in the objective, and the cholesky will fail). I can see why you might want zero noise in this case, but it isn't supported by GPflow. To get a good approximation to the noise-free model you can set the likelihood variance to `2e-6 `, and then `m.likelihood.fixed=True`.

**Comment by NazBen** [comment]
Hi @hughsalimbeni, thank you for the response. I understand it better now.

I've also forgot to set a mean_function to something linear to help fitting the data.

Thank you again.

**Comment by Like0902** [comment]
Hi,
I also come across the cholesky decomposition error. I really appreciate if someone could help. Thank you very much, and the details are as following:
File "/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
run_metadata_ptr)
File "/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
feed_dict_tensor, options, run_metadata)
File "/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
run_metadata)
File "/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cholesky decomposition was not successful. The input might not be valid.
[[Node: Cholesky = CholeskyT=DT_COMPLEX128, _device="/job:localhost/replica:0/task:0/device:GPU:0"]]
[[Node: mean_squared_error/value/_69 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_799_mean_squared_error/value", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]]

Caused by op 'Cholesky', defined at:
File "tf_graph.py", line 118, in 
l = tf.cholesky(noise_psd)
File "/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_linalg_ops.py", line 711, in cholesky
"Cholesky", input=input, name=name)
File "/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
op_def=op_def)
File "/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
op_def=op_def)
File "/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in init
self._traceback = self._graph._extract_stack() # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cholesky decomposition was not successful. The input might not be valid.
[[Node: Cholesky = CholeskyT=DT_COMPLEX128, _device="/job:localhost/replica:0/task:0/device:GPU:0"]]
[[Node: mean_squared_error/value/_69 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_799_mean_squared_error/value", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]]

**Comment by hughsalimbeni** [comment]
There are many things that could have caused this.  The `noise_psd` matrix
* may have nans somewhere
* may be ill-conditioned (increasing jitter might solve this)
* may be not even close to psd (there must be a bug somewhere)

**Comment by Like0902** [comment]
Thank you for your reply! 
I've done none check, conditioning and A=A^H check. My noise_psd matrix is complex-valued, will the complex matrix have some other concerns when doing Cholesky decomposition?

**Comment by CristinaNogRod** [comment]
Hi, I have made a custom likelihood similar to the Heteroskedastic likelihood. I am using the SVGP model and optimising with adam and nat (similar to code in the notebooks). I am getting the same error:

Cholesky decomposition was not successful for batch 0. The input might not be valid. Filling lower-triangular output with NaNs.

INVALID_ARGUMENT:  gpflow.Parameter: the value to be assigned is incompatible with this parameter's transform (the corresponding unconstrained value has NaN or Inf) and hence cannot be assigned. : Tensor had NaN values

How can I go about fixing this so that the model optimises?
