### ISSUE TITLE
Dropping python 2 support? Nice features in python 3

### ISSUE THREAD

**Issue by markvdw** [GPflow/GPflow#516]
We have had a discussion on whether to drop Python 2 support from GPflow. Currently, the consensus was lukewarmly against dropping support, on the basis that
- it doesn't currently cost a lot of effort to support python 2
- we don't use lots of python 3 specific features that really break by supporting python 2

However, I would like to keep a list of reasons to drop python 2 support, so we can be data-driven in knowing what we're giving up. From recent PRs, I have observed the following:

- Metaclasses #506 
- Non-ascii characters (can use Greek symbols to explain maths in a comment) #514
- `@` operator for matrix multiplication in both numpy and tensorflow #514 

Please add to this list, or comment with your views. It would particularly be useful to hear from people still using python 2.

**Comment by st--** [comment]
- keyword-only args ([PEP-3102](https://www.python.org/dev/peps/pep-3102/)) would make sure more complicated interfaces such as `conditionals.conditional()` are less error-prone and can be easier amended in the future (you can rely on not breaking code due to swapping around order of keyword args, etc)
- some other features (like `yield from`) that could help Artem & co write the internals in a cleaner fashion

Maybe as an initial step move to an automated 3to2 build using [pasteurize](http://python-future.org/pasteurize.html)?

**Comment by awav** [comment]
https://pythonclock.org/

**Comment by john-bradshaw** [comment]
enums in Python 3.4 (although they have been backproted: https://pypi.python.org/pypi/enum34)

**Comment by awav** [comment]
`GPflow-1.0` will support only python >= 3.
