### ISSUE TITLE
Update documentation for GPflow 1.0.0

### ISSUE THREAD

**Issue by awav** [GPflow/GPflow#548]
Documentation at http://gpflow.readthedocs.io/en/latest/ doesn't much GPflow 1.0.0.

**Comment by alexisboukouvalas** [comment]
hi @awav @alexggmatthews @jameshensman @markvdw 
I have recently gone through updating my [branching GP code](https://github.com/ManchesterBioinference/BranchedGP) to GPflow 1.0. I am including my notes from that exercise that I hope you will find useful for the documentation since it's from the perspective of being familiar with the old GPflow framework but not at all so with the new framework. 

Notes
----
1. Use defer_build to call compile explicitly:
    with gpflow.defer_build():
        m = GPflow.models.GPR(X, Y, kern=kern, mean_function=mean)
        m.compile()
        
1. Use set_trainable(False) to fix variables
    likelihood.variance.set_trainable(False)
This includes nice additional checking, e.g. setting trainable on DataHolder results in error

1. Get all parameterrs in model:	(thanks @markvdw )
param_dict = {p[0].full_name.replace('SGPR', 'SGPU'): p[1] for p in zip(vfe.trainable_parameters, vfe.read_trainables())}
	
Updates required in my code
----
1. float_type = gpflow.settings.dtypes.float_type -> settings.tf_float 

1. Autoflow -> 
    @autoflow()
    @gpflow.params_as_tensors
Need second decorator if using Params

1. Rename methods and add necessary decorators
build_likelihood -> 
@params_as_tensors
_build_likelihood

build_predict ->
@params_as_tensors
def _build_predict

1. Need to pepper in @params_as_tensors at all functions that handle tensors
(e.g. new kernels K() and Kdiag functions)

1. new paths
gpflow.model.GPModel -> gpflow.models.model.GPModel

1. optimisation - default using SciPy optimizer.
m.optimize(maxiter=maxiter) -> gpflow.train.ScipyOptimizer().minimize(m, maxiter=maxiter)

1. defer compilation when adding priors after model construction:
with gpflow.defer_build():
    k = gpflow.kernels.Matern52(1, lengthscales=0.3)
    m = gpflow.models.GPR(np.zeros((2, 1)), np.ones((2, 1)), k)
    m.likelihood.variance = 0.01
    m.kern.lengthscales.prior = gpflow.priors.Gaussian(2, .1)
    m.compile()

**Comment by st--** [comment]
Thanks, Alexis, very helpful notes. Would be good to see these in the documentation!
