### ISSUE TITLE
Test for param assignment in different sessions?

### ISSUE THREAD

**Issue by st--** [GPflow/GPflow#557]
I.e. assign a param to 2, assign it to 3 in a separate session, and check that param.value (property) returns 2, param.read_value(default_session) return 2, param.read_value(other_session) returns 3...

**Comment by awav** [comment]
There are three important things: `read_value`, `assign` and `anchor`

* The `anchor` is important because different sessions may have different values for the same tensors and `anchor` dumps values from particular session to internal parameter's cache. For e.g. all optimizer minimize function have by default `anchor=True`, it means that whenever minimize is finished, the values of trainables will be stored in parameter's internal caches.
* `read_value` w/o session reads value without touching session at all.
* `read_value` w/ session read value from particular session.
* `assign` writes value inside parameter and loads it either into specified session or if it is empty to *default gpflow session* - `gpflow.get_default_session()`.

I propose to change logic of assign: _the assign should re-write internal parameters cache only when user doesn’t pass session and the same value must also be written to the default session, but when user passes session explicitly - internal cached value should stay the same as before assignment, the value inside user's passed session will only be changed._

**Comment by jameshensman** [comment]
This comment should be in the documentation. It makes so many things clearer.

**Comment by jameshensman** [comment]
Your proposed changes to how the session/assign works make a lot of sense to me.

**Comment by st--** [comment]
No longer relevant with gpflow-2.0
