### ISSUE TITLE
active_dims slice error

### ISSUE THREAD

**Issue by Joshuaalbert** [GPflow/GPflow#631]
The assertion statement at https://github.com/GPflow/GPflow/blob/master/gpflow/kernels.py#L58
fails with a slice. E.g.
```
gp.kernels.RBF(2,active_dims = slice(0,2,1))
```
results in,
```
--> 58                 assert len(range(*active_dims)) == input_dim  # pragma: no cover
     59         else:
     60             self.active_dims = np.array(active_dims, dtype=np.int32)

TypeError: type object argument after * must be an iterable, not slice
```

## System
Python 3.6

**Comment by rhaps0dy** [comment]
The intention of the developers was probably to do:

```py
assert len(list(range(active_dims.start, active_dims.stop, active_dims.step))) == input_dim
```

since `slice` takes the same conceptual arguments as `range`. It seems like a holdover from python2 (because in python3, `len(range())` never worked), but `slice` wasn't an iterable there either.

Try modifying it and perhaps making a pull request

**Comment by Joshuaalbert** [comment]
Yes this is probably what was intended. I have a PR open at the moment. I can include it there if that's okay.

**Comment by rhaps0dy** [comment]
You should probably make a separate PR if this is a separate issue, so that your patches for whatever you're working on and this can be evaluated on their own merits. Though I can't [find any PRs from you](https://github.com/GPflow/GPflow/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3AJoshuaalbert) , maybe you haven't requested the pull yet?

**Comment by Joshuaalbert** [comment]
Ah, yes I haven't requested the pull yet, since I'm still working out a detail. And, okay two forks it is.

**Comment by markvdw** [comment]
Thanks guys. We do appreciate separate PRs for separate improvements :)
