### ISSUE TITLE
Display Loss  during Optimization

### ISSUE THREAD

**Issue by SebastianPopescu** [GPflow/GPflow#637]
Hi there,

This might sound silly but how do I manage to display the loss at each iteration of the optimization process?

**Comment by markvdw** [comment]
Check out https://github.com/markvdw/gpflow-monitor/ :)

**Comment by SebastianPopescu** [comment]
Thanks a lot ! Does seem like a pretty byzantine process just to print the ELBO.

**Comment by markvdw** [comment]
It does a lot more than just printing the ELBO :) Take a look at the example notebook.

The process is a bit byzantine. This is partly the nature of using Tensorflow -- the ELBO is never returned to Python during optimisation, and partly due to that it can be easy to add a quick fix of logging optimisation, but hard to do things in general. The gpflow-monitor tool does things in general.

**Comment by vdutor** [comment]
Hi,
I haven't tried this in GPflow 1.0, but previously if you used the `ScipyOptimizer` you can pass the `disp=1` argument to print the intermediate loss values.
