### ISSUE TITLE
How to specify a GP-LVM with p(x)~GP 

### ISSUE THREAD

**Issue by DragonCircle** [GPflow/GPflow#733]
the original setting of latent space p(X) is i.i.d Gaussian distribution.
However, I want to place a Gaussian Processes prior on the latent space p(X)~GP(0,k_{t,t'})
Is GPflow able to do this?
If can, how?
Please!

**Comment by hughsalimbeni** [comment]
There's a paper that does exactly this http://papers.nips.cc/paper/4330-variational-gaussian-process-dynamical-systems.pdf, but now we'd refer to this as a deep gp. If you apply natural gradients to https://github.com/ICL-SML/Doubly-Stochastic-DGP you get very nearly the same inference (it doesn't use the kernel expectations, but including them is fairly straightforward). I'm planning to put up an example of this soon.

**Comment by DragonCircle** [comment]
Thank you for your response!

As far as I know, the latent space of GPDM is under Markov assumption.
That's a natural choice to make t+1 prediction.
However, in the V-GPDM paper, the latent space is a GP prior for smoothing, **how to make t+1 prediction?**
I don't know if this is a naive question because I am not familiar with recent GP papers.

**Comment by markvdw** [comment]
From memory (it's been years since I read that paper) you should use the usual GP predictive distribution to get a the distribution in the latent space for the next t+1, and then pass this through the GP from the latent space to the observations and the likelihood. Hope this is a reasonable hint.

Feel free to reply again, but I'm closing this issue since it's more of a general GP question rather than an actual issue with the software.
