### ISSUE TITLE
Eager mode

### ISSUE THREAD

**Issue by nrontsis** [GPflow/GPflow#779]
I wonder if there is any plan on adopting TensorFlow's [Eager Execution](https://www.tensorflow.org/programmers_guide/eager). I believe, that there might be a lot of benefits, including
- significantly easier debugging;
- simplified/more transparent core of GPflow (autoflow etc)

**Comment by markvdw** [comment]
GPflow has a focus on scalability. We're interested in Eager, mostly since it seems like a good way of prototyping code. We're interested into figuring out whether Eager can make our lives easier, but not spending all too much time on this right now.

If you have any suggestions, or examples of use cases, this would be really interesting to see!
