### ISSUE TITLE
Ability to integrate interdomain inducing point methods with GPflow 

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#8]
Some GPflow users are interested in interdomain inducing points. At the moment it is a little fiddly to integrate their code with the main code base. We should think about making it easier without disrupting the main code base.

**Comment by markvdw** [comment]
I've pushed the branch `inter-domain`. It has as working implementation of the inter domain GP, which is demonstrated in the notebook. A few unittests may fail since it's not easy to generally find `Kzx` and `Kzz` for `kernels.Prod`.

I'll take a look if I can adjust the unittests appropriately soon.

**Comment by markvdw** [comment]
Ok all unittests run. The thing that still needs to be checked is whether `gp_predict`, `gaussian_gp_predict` and `gaussian_gp_predict_whitened` are only used by inducing point methods. If this is the case, then everything's ready to go. I've searched through the usages of these functions and currently I can't find any usages other than in `SVGP`. Though I don't know what your plans for the future are.

If this is *not* the case (or perhaps in the future) then things are more complicated, since `Kzx` and `Kzz` need to be used when inducing variables are considered, and `K` should just be used in other cases. This may require adding a switching parameter or something.

**Comment by st--** [comment]
Superseded by #530
