### ISSUE TITLE
Question on full covariance for q and whitening

### ISSUE THREAD

**Issue by atechnicolorskye** [GPflow/GPflow#801]
Hi,

I'm just curious about how we should go about setting q_diag in the case of SVGP. From the code (see models/svgp.py), it seems by default we initialise q with a [full covariance matrix](https://github.com/GPflow/GPflow/blob/1b0f4b084fed09a2287aaa175c24f36da1d45b00/gpflow/models/svgp.py#L49) but on the other hand the default output would not have both [full covariance and full covariance output](https://github.com/GPflow/GPflow/blob/1b0f4b084fed09a2287aaa175c24f36da1d45b00/gpflow/models/svgp.py#L158). Empirically, does having q with a full covariance improve performance in terms of log loss?

Also, when performing VI, how much does whitening help? It seems that [this](https://github.com/GPflow/GPflow/issues/578) shows that it helps with the scipy optimiser... And also would it be possible to recover the unwhitened representation at the end?

Cheers,
Sky

**Comment by hughsalimbeni** [comment]
* q_sqrt being diagonal is not relevant for whether the conditional is diagonal. The term coming from q_sqrt is given by L^TL where L=q_sqrt Kmm^-1 Km*, which has non-zero off-diagonal entries even if q_sqrt is diagonal. 

* Empirically, I'd say that we're lacking an experiment to determine how much difference the off-diagonals of q_sqrt make in practice. It's a necessarily better approximation with a full q_sqrt, but whether the gain is worth it in practice isn't obvious. As far as I know, there aren't any publicly reported results explicitly comparing this, but I think it should be done. Such an experiment might fit within the scope of https://github.com/hughsalimbeni/bayesian_benchmarks. If you'd like to open a PR in that repo and run the diag model I'd be very interested to see what the results are!

* Related to #800, the diagonal approximation can be a bit weird because the square root depends on the column ordering. I've noticed odd things happening, e.g. in a symmetric problem you can get asymmetric posteriors with the diagonal approximation. 

* Regarding whitening, again I haven't seen good experiments to show how useful it is in practice. In my own experience suggests that it often makes things worse, unless the between inducing point correlations are strong (ie Kmm is ill conditioned). Note that 1D examples can be misleading about behaviour in general: it is certainly true that in 1D with lots of inducing points whitening is very beneficial, but this is a special case. As a plug: one advantage of the [natural gradient optimizer](https://arxiv.org/pdf/1803.09151.pdf) is that it avoids these problematic algorithm issues by updating the variational parameters in their own geometry.

**Comment by markvdw** [comment]
I agree with @hughsalimbeni. One thing to add, is the more inducing points you have, the more the true optimal variational posterior will be diagonal (the classic Opper & Archambeau paper).

**Comment by atechnicolorskye** [comment]
Thanks for the quick replies 👍 , @hughsalimbeni I'll look into your benchmarks when I have the time
