### ISSUE TITLE
Autoflow fails after resizing of variables

### ISSUE THREAD

**Issue by markvdw** [GPflow/GPflow#81]
Hi all,

I'm worried Autoflow still isn't working as expected. I'm on the latest commit. Below is an experiment where I add an extra inducing point. I think the bound calculation is good, but the predictions are different if I copy the parameters over to a new model.

Haven't had the chance to investigate thoroughly yet, but I thought I'd share.

[edit] More concise piece of code plus a workaround. The problem is that after adding the new inducing point, the prediction `py2` is the same as the prediction `py1`. Only after deleting the prediction graph, do I get a correct prediction.

```
import numpy as np
import matplotlib.pyplot as plt
import GPflow
import datasets

Y, X, _, _ = datasets.load_data('snelson1d')
m = GPflow.sgpr.SGPR(X, Y, GPflow.kernels.RBF(1), Z=np.random.rand(2, 1)*np.max(X))

py1, pyv1 = m.predict_y([[3]])

Z = m.Z._array.copy()
m.Z._array = np.vstack((Z, [3]))  # Add an extra inducing point
m._compile()                               # Compile to ensure correct parameter mapping

py2, pyv2 = m.predict_y([[3]])

delattr(m, '_predict_y_graph')
py3, pyv3 = m.predict_y([[3]])

print py1
print py2
print py3
```

**Comment by markvdw** [comment]
Ok, so I've looked into this issue a bit more, and I think I've found the root cause. I've edited the code above to give a more concise example.

The problem is that when I change the size of `Z`, `predict_y` still only "sees" the old size of `Z`. I confirmed this by adding a print op in `build_predict`. The problem is that after `Z` has changed size, `predict_y` still lifts the old indices out of `_free_vars`, since it hasn't been re-run after the `_compile()`.

I admit this is a bit of an edge case, but it would be fixed by re-creating the graph at every call. This slows down a call by ~200ms in some simple tests for me (from just a few ms).

Any ideas on how to fix this? Or whether to even bother? I've got a workaround now, so I'm fairly happy...

**Comment by jameshensman** [comment]
I'm not sure this is a bug: the convention is that since `Param._array` starts with an underscore, you shouldn't really be accessing it. In other languages this would be a private variable. 

The correct way to assign to a `Param` is to use assignment (!), i.e.
```python
m = GPflow.sgpr.SGPR(X, Y, Z, ...)
new_Z = np.random.randn(10, 1)
m.Z = new_Z
```

of course this fail if your `new_Z` is the wrong shape. So I guess the correct thing to do would be
```python
m = GPflow.sgpr.SGPR(X, Y, Z, ...)
new_Z = np.random.randn(10, 1)
m.Z = GPflow.param.Param(new_Z)
```
but I'm not sure that will flip the `_needs_recompile` bool, to tell the model to recompile. That's an easy fix. 

It strikes me that there's a minor design flaw in this comment: it you're not supposed to use `Param._array`, then how should you get at the result? Well, I suggest we add a `Param.value` property, so that the value of the parameter can be retrieved, but only set through the assignment.

**Comment by markvdw** [comment]
Merged, and closed.
