### ISSUE TITLE
Question: Multiple-view Classification

### ISSUE THREAD

**Issue by DJArmstrong** [GPflow/GPflow#834]
I am trying to set up a classification model where each input data has multiple 'views'. i.e. where the inputs might take the form:

X_train = np.vstack(( np.hstack(( class1_view1 , class1_view2 )),
                                    np.hstack(( class2_view1 , class2_view2 ))
                                   ))
Y_train = np.hstack((np.zeros(class1),np.ones(class2)))

I know I can apply different kernels to the two views using active_dims, but is there any way of applying different likelihoods in the same way? Each view will have different (internally consistent) noise properties, as well as different dimension.

Alternatively, is there a better way to set up such a model? I looked at the Coregionalization example but couldn't see how to apply it to a classification problem. Putting different views as different rows in X would allow using SwitchedLikelihood but makes it difficult to use both views simultaneously to predict unclassified examples, unless I've misunderstood. Thanks for any help you can give.

**Comment by hughsalimbeni** [comment]
Your question is a good one, but the solution requires further research and is beyond the scope of gpflow. The difficulty here is that you have a covariate that is partially observed (i.e. present in the training but not the test inputs). What makes this more tricky is that the gplvm-style (see e.g. [this](https://arxiv.org/abs/1604.04939) paper) approach for this won't work straightforwardly as you have a discrete variable.

**Comment by DJArmstrong** [comment]
I'm not sure I understand - both views would be available for training and testing inputs, so I can always create an 'X' of the same form to pass to the trained GP.

**Comment by st--** [comment]
Dear @DJArmstrong, this seems more of a "how-to" question and as such would be more appropriate to stackoverflow - so that other people who may have similar questions in the future can more easily benefit from the discussion - it'd be great if you could post it there, tagged "gpflow" (https://stackoverflow.com/questions/tagged/gpflow), and add any further comments/insights you may have gained in the meantime - if you've managed to find an answer by now, it'd be great if you could post that on stackoverflow, too! I hope this makes sense :-)
