### ISSUE TITLE
Syntax error in documentation

### ISSUE THREAD

**Issue by markmoses** [GPflow/GPflow#841]
Hey all,

I am reading the page below of the docs and noticed the line of code `m.kern.coregion.W = np.random.randn(2, 1)` does not work when I am on gpflow ver 1.2. I guess more specifically, how do you pass values to the `W` parameter? I called dir on the kernel and did not see the coregion kernel listed. Is there something I am missing? Thanks!

https://gpflow.readthedocs.io/en/latest/notebooks/coreg_demo.html

**Comment by st--** [comment]
Ah, what happened is that accessing elements of sum or product kernels by name got deprecated (it was a lot of internal hassle having to keep track of two separate ways of accessing them), now you need to do `kern.kernels[1].W = ...` - or, if you still have the handle to the Coregion kernel object, `coreg.W = ...`. We've got notebook tests but they only check that the code runs through and have no way of testing the output still makes sense (the `m.kern.coregion.W = ...` line simply added a new attribute to the product kernel that then wasn't used anywhere; valid code but useless) - so thanks for spotting this! Will fix this tomorrow.

**Comment by markmoses** [comment]
Cool. Thanks! Along the same lines is there a way to access the number of iteration a model went through using one of the tf optimizers or a scipy optimizer ? so in the code in the link above you all have `gpflow.train.ScipyOptimizer().minimize(m)`  is there an object stored in `m` with the num of iteration it went through? Thanks!

**Comment by st--** [comment]
@markmoses For the TF optimizers such as AdamOptimizer, you have to specify for how many steps to run them in the first place. For the ScipyOptimizers, you'd have to hack the code, I think the following might work:
- in gpflow/training/scipy_optimizer.py, ScipyOptimizer.minimize, store the result of optimizer.minimize() in line 88, and add another line after line 91 to return this result.
- in gpflow/training/external_optimizer.py, ScipyOptimizerInterface._minimize, change line 444 to return the entire `result` object instead of just `result['x']`.
Then you can access result.nit ...

**Comment by st--** [comment]
Turns out the notebook was actually corrected before, but readthedocs is showing an outdated version :/ if you select "master" it's correct. (We'll have to set up something for the new[ish] develop branch there...)

**Comment by st--** [comment]
@markmoses actually you would also have to change the ExternalOptimizerInterface (which calls the _minimize of ScipyOptimizerInterface), so it'd take a bit more thought to make this work in gpflow "out of the box". Please open a new issue about that if it's something you care about!

The documentation is now up to date, so I'm closing this issue.
