### ISSUE TITLE
Fitting either Independent or AR(1) GPs

### ISSUE THREAD

**Issue by sadatnfs** [GPflow/GPflow#860]
Hello!

Out of curiosity, has anyone worked on implementing an IID esque or AR(1) kernel in their GPFlow models? I would like to have an independent country "random effect" and an autoregressive correlation across another categorical variable, and so I wanted to check if anyone else has already implemented it before I look into all the math and start customizing things myself.

Thanks!

**Comment by st--** [comment]
Dear @sadatnfs, it would be great if you could post this as a question on stackoverflow (tagged gpflow: https://stackoverflow.com/questions/tagged/gpflow), whether you're still looking for an answer or found it (in which case I would encourage you to answer it yourself) so that future users can also benefit. Hope that makes sense!
