### ISSUE TITLE
Flexibility in mean functions to mimic random effects models

### ISSUE THREAD

**Issue by sadatnfs** [GPflow/GPflow#880]
Hello,

I was wondering if it's possible to maybe implement custom mean functions in a GPFlow model? The use case I have is to fit a model of the following type:

```
Y_{c,t} = alpha + alpha_c + beta * X_{c,t} + (Time GP_t)
alpha_c ~ Normal(0., sigma_a)
GP_t ~ Matern52(., .)
```

Therefore, the mean function I'd like to feed into the GP would be `alpha + alpha_c + beta*X`, where `alpha_c` is a random effect on the `c` dimension, and the GP is on the `t` dimension.

The reason why I'd like to fit a model like this is to be able to model a mixed effects regression with GP errors. In Tensorflow, I can do something like `tf.gather(parameter_vector, vector_of_indices_indicating_different_c), which will do like a matrix multiplication of the index and the associated parameter we're fitting on the random effect. But I'm not sure if it'd be possible to feed that into GPFlow.

The alternative I've tried is to learn from GPFlow's source code on how the kernel and GP is build so that I can feed the GPs into raw TensorFlow code, but that went over my head a lot faster...

Any tips would be great! Thanks!

**Comment by st--** [comment]
Dear @sadatnfs, sorry for the delay in replying (it's mostly in our spare time that we deal with maintaining gpflow!) - it's definitely possible to feed tensorflow tensors into GPflow, e.g. see https://nbviewer.jupyter.org/github/GPflow/GPflow/blob/develop/doc/source/notebooks/tailor/external-mean-function.ipynb - if that doesn't answer your question already, it'd be great if you could post this as a question on stackoverflow (tagged gpflow: https://stackoverflow.com/questions/tagged/gpflow), so that future users can also benefit. Hope that makes sense!
