### ISSUE TITLE
Tracking session in gpflow

### ISSUE THREAD

**Issue by JSP21** [GPflow/GPflow#886]
With respect to the code in https://github.com/GPflow/GPflow/blob/develop/gpflow/conditionals.py
what is the proper way to tap the session of Xnew inside the: "@conditional.register(object, object, Kernel, object) @name_scope("conditional") def _conditional(Xnew, X, kern, f, *, full_cov=False, q_sqrt=None, white=False):" method. And how to actually view the value of Xnew in ndarray format inside _conditional method.

**Comment by vdutor** [comment]
Hi @JSP21 
Thank you for your question and interest in GPflow. We're happy to answer your question but would need a bit more information on what exactly you are trying to achieve. A minimal failing/working example would be great.

That said, we are trying to build some momentum around stack overflow, and we're trying to answer this type of question on that platform - rather than as GitHub issues. Could you, therefore, please repeat your question on stack overflow using the `gpflow` tag and post the link here. Thank you
