### ISSUE TITLE
Support for Uncertain Inputs

### ISSUE THREAD

**Issue by sahandrez** [GPflow/GPflow#893]
Hello,
 
Does this package supports uncertain inputs during the prediction step? What about uncertain inputs during the training step? 
I looked around and it seems there is no information on that. 

Thanks, 
Sahand

**Comment by markvdw** [comment]
Hi Sahand,

Currently, there is a good deal of back-end code that makes this easy, but the front-end functionality is not there yet. `conditionals.py:uncertain_conditional()` is designed for exactly this. It calculates the moment matched means and variances for Gaussian inputs, which is also what is needed for GPLVMs and variational uncertain input models. To train with this, one needs to implement a model using this conditional instead of the normal one, and similarly for testing.

Hope this helps.

**Comment by PeterMitrano** [comment]
I'd just like to add my :+1: for this being a great feature to include. I would imagine something like `model.predict_y/f_gaussian` or `model.predict_y/f_uncertain`. Would such a PR be welcome?

**Comment by LCanas** [comment]
@markvdw Thanks for this clarification. I couldn't find though the conditionals.py:uncertain_conditional(). Can you help me with this?

**Comment by st--** [comment]
@PeterMitrano I think it would be great to include such a feature - at this point it should go straight into gpflow2 though, for compatibility with tensorflow 2.0+ (see the `develop-2.0` branch)!

@LCanas: https://github.com/GPflow/GPflow/blob/164d90d78c1c6fd966ae19ebaee59b9241bcba39/gpflow/conditionals.py#L265

**Comment by rcameronc** [comment]
@st--, @markvdw , and others, thanks for creating such a well-written, powerful library. 

 Is the `uncertain_conditional` function an instantiation of the McHutchon & Rasmussen 2011 Noisy Input Gaussian Process (https://papers.nips.cc/paper/4295-gaussian-process-training-with-input-noise), or does this serve a different purpose?  If the latter, have there been any discussions about incorporating NIGP into GPflow?

**Comment by st--** [comment]
@rcameronc only just spotted your message! In the future, if you want to make sure to get an answer, best to re-open an issue :) `uncertain_conditional` isn't used for anything within GPflow-core - we've used it for implementing various code for papers that hasn't yet been open-sourced. If you want to implement NIGP on top of gpflow, that'd be great! You're welcome to join the chat on gpflow.slack.com (invite link is in the GPflow README.md) if you want to discuss it with others or need some support with that. I don't know if we'd incorporate NIGP into GPflow-core, but we would probably be happy to consider adding it as another notebook example, or you can host it on your own github and we link to it from GPflow's README. :)

**Comment by Vasile-Ciorna** [comment]
@st-- , @markvdw, @vdutor, @uri-granta, @awav   Hello and sorry if this is asked in the wrong place.  I see the gpflow API reference having the uncertain conditional [here](https://gpflow.github.io/GPflow/develop/api/gpflow/conditionals/index.html#gpflow-conditionals-uncertain-conditional) but looking in the API ref or in the code (or associated commits) have not seen any reference or paper of where this implementation is coming from.  Would this implementation be coming from Girard et al. paper [here](https://proceedings.neurips.cc/paper_files/paper/2002/file/f3ac63c91272f19ce97c7397825cc15f-Paper.pdf) ?  Is there any example somewhere documented of how to use it? 
I have also seen this [discussion](https://github.com/GPflow/GPflow/issues/2090), but the answers are more related to propagating output uncertainty or variable output uncertainty rather than input uncertainty, if I'm not wrong.

Thanks in advance.
