### ISSUE TITLE
Bernoulli log probability under probit link

### ISSUE THREAD

**Issue by tohein** [GPflow/GPflow#955]
Hi, 
thanks for your great work on this framework! 
I have some doubt regarding the Bernoulli likelihood module. Plotting the log likelihood for a probit model, 
```
import tensorflow as tf
from gpflow.likelihoods import Bernoulli
import matplotlib.pyplot as plt

bernoulli_lik = Bernoulli()
sess = tf.Session()
with sess.as_default():
    F = tf.lin_space(-10., 10., 100)
    y = tf.log(bernoulli_lik.invlink(F))
    plt.plot(F.eval(), y.eval())
    plt.savefig('log_cdf.pdf')
```
gives
![log_cdf](https://user-images.githubusercontent.com/19325791/54536625-53693480-4991-11e9-8d95-08ac22bf1055.png)
Did you think about implementing the logcdf? Does it even make a difference? Or is the function intended to bottom out at -6.9 (e.g. numerical reasons)?

Best,
Tobi

**Comment by st--** [comment]
Hi Tobi, if you look at the output of the `inv_probit()` function directly (not in log-space) or go through the code carefully, you'll see that the output is clamped between 0.001 and 0.999. This is intentional (if you set the `jitter` constant in that function to zero, you get the exact cdf back), I think for reasons of numerical stability (otherwise the log-probability would shoot off for very solitary outliers in regions where almost all observations are of the other class), though I also have to admit this is one of the oldest parts of GPflow so maybe it is not *actually* necessary in practice or there *are* other, better ways to deal with it - but this also suggests the code generally does what it is intended to :) You're very welcome to experiment with it, and if you think you find a way to improve the code (whether in the Bernoulli likelihood or elsewhere), please open a pull request! Hope this helps:)
