### ISSUE TITLE
Considering observation error

### ISSUE THREAD

**Issue by koneshgit** [GPflow/GPflow#959]
## Including observation error in regression ##

I want use GPFlow's regression to interpolate  a V (variable) in my X,Y,Z space. Observations are noisy (supposed Gaussian) represented by Sigma_V at each observed point. I want include Sigma_V as [Alpha in SK-Learn's GP](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html). such that estimator can work for estimation of any sub space. 

I mean the the length of target (_new) is not fixed in:
` V_new = GPR ([x_new, y_new,z_new] | kern, xobs, yobs ,zobs, Vobs, Vobs_std))`
___

... Are you willing to contribute it (Yes/No):
Yes
... _Describe the feature and the current behavior/state_

... _Will this change the current api? How?_

.. _Who will benefit with this feature?_

.. _Any other info_

**Comment by vdutor** [comment]
Hi @koneshgit 

First of all, thanks for your question and for trying out GPflow!

We, however, use these GitHub issues for actual issues/bugs in GPflow, rather than for helping with individual use-cases. Therefore, could you please repost your question on StackOverflow using the `GPflow` tag (https://stackoverflow.com/questions/tagged/gpflow). We monitor this activity and will be happy to answer your question there. Also, don't forget to add a minimal working/failing example, so for us to help you as efficiently as possible.

I'll close this issue for now -- please feel free to reopen if this is actually a bug.

**Comment by st--** [comment]
@koneshgit we now have a new notebook explaining how to build a model with varying noise: https://nbviewer.jupyter.org/github/GPflow/GPflow/blob/develop/doc/source/notebooks/advanced/varying_noise.ipynb - hope you find it useful!
