### ISSUE TITLE
Kernel's hyperparameters;  initialization and setting bounds

### ISSUE THREAD

**Issue by koneshgit** [GPflow/GPflow#960]
## A full example of initialization and setting bounds of the kernel model##
I think many other people like me might be interested in how they can use GPFlow for their special problems. The key is how GPFlow is customizable, and a good example would be very helpful.

In my case, I _read and tried lots of comments_ in raised issues without any real success. Setting kernel model parameters is not straightforward (creating with default values, and then do it via the delete object method). Transform method is vague. 

It would be **really helpful** if you could add an example showing. how one can initialize and set bounds of an anisotropic kernel model (**length-scales values and bounds, variances, ...**) and specially adding **observations error** ([**as an array-like alpha parameter**](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html#sklearn.gaussian_process.GaussianProcessRegressor))

**Comment by hughsalimbeni** [comment]
If you just want to set a value, then you can do

```python
model = gpflow.models.GPR(np.zeros((1, 1)),
                          np.zeros((1, 1)),
                          gpflow.kernels.RBF(1, lengthscales=0.2))

```
Alternatively

```python
model = gpflow.models.GPR(np.zeros((1, 1)),
                          np.zeros((1, 1)),
                          gpflow.kernels.RBF(1))
model.kern.lengthscales = 0.2
```

If you want to change the transform, you either need to subclass the kernel, or you can also do

```python
with gpflow.defer_build():
    model = gpflow.models.GPR(np.zeros((1, 1)),
                              np.zeros((1, 1)),
                              gpflow.kernels.RBF(1))
    model.kern.lengthscales = gpflow.params.Parameter(0.3,
                                                      transform=gpflow.transforms.Logistic(0.1, 1.))

model.compile()
```

You need the `defer_build` to stop the graph being compiled before you've changed the transform. Using the approach above the tensorflow graph is delayed so is built with the intended bounding transform. 

Using an array parameter for likelihood variance is outside the scope of gpflow. For what it's worth (and because it has been asked about before), that particular model is especially problematic as it is not clear how test points are defined.

**Comment by hughsalimbeni** [comment]
Repeated answer [here](https://stackoverflow.com/questions/55457750/kernels-hyper-parameters-initialization-and-setting-bounds/55478125#55478125), so closing
