### ISSUE TITLE
About A Simple Demonstration of Coregionalisation in GPR model instead of VGP

### ISSUE THREAD

**Issue by ChunchaoPeter** [GPflow/GPflow#984]
Hi, 

I am new to TensorFlow and GPflow.
I tried to implement intrinsic model of coregionalization (ICM) in GPflow.  I followed your example online:  A Simple Demonstration of Coregionalisation

... _Provide documentation link:_
https://nbviewer.jupyter.org/github/GPflow/GPflow/blob/develop/doc/source/notebooks/advanced/coregionalisation.ipynb

... _Describe the documentation issue._

The original code is :

# now build the GP model as normal
m = gpflow.models.VGP(X_augmented, Y_augmented, kern=kern, likelihood=lik, num_latent=1)

I want to change the VGP to GPR (normal GP regression) as below:

# now build the GP model as normal
m = gpflow.models.GPR(X_augmented,Y_augmented, kern=kern, likelihood=lik, num_latent=1)

It is a bit weird. The ICM model can be implement by VGP. However, I do not know why the model can not implement by normal GP regression in my case.  Could you please tell me how can I implement the ICM in the normal GP regression ? 

Thanks in advance. :)

**Comment by prockenschaub** [comment]
You do not specify the exact error you are running into, but when I run the tutorial and substitute GPR vor VGP when declaring the model, the error I run into is `TypeError: __init__() got multiple values for argument 'likelihood'`.

This is because GPR already pre-specifies the likelihood to be Gaussian during its __init__ step. Passing it another likelihood as you do above leads to an error when calling the underlying GPModel.__init__:
```
# From the implementation of GPR in gpflow/models/pgr.py:

class GPR(GPModel):
    def __init__(self, X, Y, kern, mean_function=None, **kwargs):
        likelihood = likelihoods.Gaussian()    # Here a likelihood is pre-specified to be Gaussian
        X = DataHolder(X)
        Y = DataHolder(Y)

        # Here the error is thrown if **kwargs contains another parameter called likelihood
        GPModel.__init__(self, X, Y, kern, likelihood, mean_function, **kwargs) 
```


To get rid of the error, just run the call as you state above without the likelihood argument, which should give you the desired model. 

`m = gpflow.models.GPR(X_augmented,Y_augmented, kern=kern, likelihood=lik, num_latent=1)`

**Comment by ChunchaoPeter** [comment]
Thanks for your help.
